// web/src/views/LogsView.vue
<template>
  <div class="detail-page process-logs-page">
    <div class="page-head">
      <h2 class="page-title">{{ t('logs.title') }}</h2>
      <div class="logs-toolbar">
        <el-radio-group v-model="scope" size="small" @change="handleScopeChange">
          <el-radio-button value="server">{{ t('logs.server') }}</el-radio-button>
          <el-radio-button value="agent">{{ t('logs.agent') }}</el-radio-button>
        </el-radio-group>
        <el-select
          v-if="scope === 'agent'"
          v-model="selectedAgentId"
          size="small"
          clearable
          filterable
          :placeholder="t('logs.agentPlaceholder')"
          style="width: 240px"
          @change="handleAgentChange"
        >
          <el-option
            v-for="agent in agents"
            :key="agent.id"
            :label="`${agent.name} (${agent.hostname})`"
            :value="agent.id"
          />
        </el-select>
        <el-select
          v-model="levelFilter"
          size="small"
          clearable
          :placeholder="t('logs.filters.level')"
          style="width: 150px"
          @change="handleFilterChange"
        >
          <el-option :label="t('logs.filters.allLevels')" value="" />
          <el-option
            v-for="level in LOG_LEVELS"
            :key="level"
            :label="t(`logs.levels.${level}`)"
            :value="level"
          />
        </el-select>
        <el-select
          v-model="typeFilter"
          size="small"
          clearable
          :placeholder="t('logs.filters.type')"
          style="width: 170px"
          @change="handleFilterChange"
        >
          <el-option :label="t('logs.filters.allTypes')" value="" />
          <el-option
            v-for="type in LOG_TYPES"
            :key="type"
            :label="t(`logs.types.${type}`)"
            :value="type"
          />
        </el-select>
        <el-button size="small" :loading="loading" @click="loadLogs(true)">
          <el-icon><Refresh /></el-icon>
          <span>{{ t('common.refresh') }}</span>
        </el-button>
      </div>
    </div>

    <el-alert
      v-if="scope === 'agent' && !selectedAgentId"
      :title="t('logs.selectAgentHint')"
      type="info"
      :closable="false"
      show-icon
      style="margin-bottom: 16px"
    />

    <div v-if="error" class="error-state">
      <el-icon><Warning /></el-icon>
      <p>{{ error }}</p>
      <el-button type="primary" @click="loadLogs(true)" style="margin-top: 12px">
        {{ t('common.retry') }}
      </el-button>
    </div>

    <el-card v-else shadow="never" class="logs-card">
      <template #header>
        <div class="logs-header">
          <span>{{ currentTitle }}（{{ logs.length }}）</span>
          <el-button
            type="primary"
            size="small"
            :disabled="loading || !hasMore"
            @click="loadMore"
          >
            {{ loading ? t('logs.loading') : t('logs.loadMore') }}
          </el-button>
        </div>
      </template>

      <div v-if="loading && logs.length === 0" class="logs-loading">
        <el-icon class="is-loading"><Loading /></el-icon>
      </div>
      <el-empty v-else-if="logs.length === 0" :description="t('logs.empty')" />
      <el-table v-else :data="displayLogs" stripe size="small" max-height="620">
        <el-table-column :label="t('logs.columns.id')" width="92">
          <template #default="{ row }">
            <code>{{ row.id }}</code>
          </template>
        </el-table-column>
        <el-table-column :label="t('logs.columns.type')" width="130">
          <template #default="{ row }">
            <el-tag size="small" type="info">{{ typeText(row.type) }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column v-if="scope === 'agent'" :label="t('logs.columns.sourceSeq')" width="92">
          <template #default="{ row }">
            {{ row.source_seq ?? '-' }}
          </template>
        </el-table-column>
        <el-table-column :label="t('logs.columns.time')" width="190">
          <template #default="{ row }">{{ formatTime(row.timestamp) }}</template>
        </el-table-column>
        <el-table-column :label="t('logs.columns.level')" width="92">
          <template #default="{ row }">
            <el-tag size="small" :type="levelTagType(row.level)">{{ row.level }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column :label="t('logs.columns.message')" min-width="420">
          <template #default="{ row }">
            <span class="process-log-message">{{ row.message }}</span>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { apiGet } from '@/api/client'
import type { Agent, SystemLog } from '@/api/types'
import { formatDateTime, translateEnum } from '@/i18n'

const PAGE_SIZE = 500
const LOG_LEVELS = ['debug', 'info', 'warn', 'error'] as const
const LOG_TYPES = ['system', 'http', 'agent', 'run', 'scheduler', 'dispatcher', 'connection', 'command', 'notification'] as const
const route = useRoute()
const router = useRouter()
const { t } = useI18n()

type LogScope = 'server' | 'agent'

const initialAgentID = typeof route.query.agent_id === 'string' ? route.query.agent_id : ''
const scope = ref<LogScope>(initialAgentID ? 'agent' : 'server')
const selectedAgentId = ref(initialAgentID)
const levelFilter = ref('')
const typeFilter = ref('')
const agents = ref<Agent[]>([])
const logs = ref<SystemLog[]>([])
const loading = ref(false)
const error = ref('')
const hasMore = ref(false)

const currentTitle = computed(() => {
  if (scope.value === 'server') return t('logs.server')
  const agent = agents.value.find((item) => item.id === selectedAgentId.value)
  return agent ? t('logs.agentTitle', { name: agent.name }) : t('logs.agent')
})

const displayLogs = computed(() => [...logs.value].sort((a, b) => b.id - a.id))

function formatTime(value: string): string {
  return formatDateTime(value)
}
function typeText(type: string): string {
  return translateEnum('logs.types', type)
}


function levelTagType(level: string): 'info' | 'success' | 'warning' | 'danger' {
  switch (level) {
    case 'error':
      return 'danger'
    case 'warn':
      return 'warning'
    case 'debug':
      return 'info'
    default:
      return 'success'
  }
}

function endpoint(): string | null {
  if (scope.value === 'server') return '/logs/server'
  if (!selectedAgentId.value) return null
  return `/agents/${encodeURIComponent(selectedAgentId.value)}/logs`
}

async function loadAgents(): Promise<void> {
  try {
    agents.value = await apiGet<Agent[]>('/agents')
  } catch {
    agents.value = []
  }
}

async function loadLogs(reset: boolean): Promise<void> {
  const path = endpoint()
  if (!path) {
    logs.value = []
    hasMore.value = false
    return
  }
  loading.value = true
  error.value = ''
  try {
    const beforeId = reset || logs.value.length === 0 ? undefined : Math.min(...logs.value.map((item) => item.id))
    const data = await apiGet<SystemLog[]>(path, {
      limit: PAGE_SIZE,
      before_id: beforeId,
      level: levelFilter.value || undefined,
      type: typeFilter.value || undefined,
    })
    const merged = reset ? data : [...data, ...logs.value]
    const byID = new Map<number, SystemLog>()
    for (const entry of merged) byID.set(entry.id, entry)
    logs.value = Array.from(byID.values())
    hasMore.value = data.length === PAGE_SIZE
  } catch (err: any) {
    error.value = err.message || t('logs.loadFailed')
  } finally {
    loading.value = false
  }
}

function handleFilterChange(): void {
  logs.value = []
  hasMore.value = false
  void loadLogs(true)
}

async function loadMore(): Promise<void> {
  if (loading.value || !hasMore.value) return
  await loadLogs(false)
}

function handleScopeChange(): void {
  logs.value = []
  hasMore.value = false
  if (scope.value === 'server') {
    selectedAgentId.value = ''
    void router.replace({ query: {} })
  } else {
    void router.replace({ query: selectedAgentId.value ? { agent_id: selectedAgentId.value } : {} })
  }
  void loadLogs(true)
}

function handleAgentChange(): void {
  void router.replace({ query: selectedAgentId.value ? { agent_id: selectedAgentId.value } : {} })
  void loadLogs(true)
}

watch(
  () => route.query.agent_id,
  (value) => {
    if (scope.value !== 'agent') return
    const agentID = typeof value === 'string' ? value : ''
    if (agentID === selectedAgentId.value) return
    selectedAgentId.value = agentID
    void loadLogs(true)
  },
)

onMounted(async () => {
  await loadAgents()
  await loadLogs(true)
})
</script>
<style scoped>
.detail-page {
  max-width: 1400px;
  margin: 0 auto;
}
.page-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  margin-bottom: 16px;
}
.page-title {
  margin: 0;
  font-size: 22px;
  font-weight: 600;
}
.logs-toolbar {
  display: flex;
  align-items: center;
  justify-content: flex-end;
  gap: 10px;
  flex-wrap: wrap;
}
.logs-card {
  margin-bottom: 16px;
}
.logs-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}
.logs-loading {
  display: flex;
  justify-content: center;
  padding: 40px;
}
.process-log-message {
  display: block;
  white-space: pre-wrap;
  word-break: break-word;
  font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
  line-height: 1.5;
}
@media (max-width: 760px) {
  .page-head {
    align-items: flex-start;
    flex-direction: column;
  }
  .logs-toolbar {
    width: 100%;
    justify-content: flex-start;
  }
}
</style>

// web/src/views/LogsView.tsx
import React, { useEffect, useState, useRef } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { apiGet, isApiClientError, isAbortError } from '@/api/client'
import { formatDateTime } from '@/i18n'
import type { SystemLog, Agent } from '@/api/types'
import { AppEmptyState } from '@/components/AppEmptyState'
import { AppErrorState } from '@/components/AppErrorState'
import { StatusBadge, type BadgeTone } from '@/components/StatusBadge'
import { PageLoadingState } from '@/components/PageLoadingState'
import { RefreshCw, RotateCcw, Loader2, Server, Activity, Info } from 'lucide-react'

const LOG_LEVELS = ['debug', 'info', 'warn', 'error']
const LOG_TYPES = ['system', 'http', 'agent', 'run', 'scheduler', 'dispatcher', 'connection', 'command', 'notification']

const LEVEL_TONES: Record<string, BadgeTone> = {
  debug: 'secondary',
  info: 'default',
  warn: 'warning',
  error: 'destructive',
}

export const LogsView: React.FC = () => {
  const { t } = useTranslation()
  const [searchParams, setSearchParams] = useSearchParams()

  const [scope, setScope] = useState<'server' | 'agent'>('server')
  const [selectedAgentId, setSelectedAgentId] = useState<string>('')
  const [levelFilter, setLevelFilter] = useState<string>('all')
  const [typeFilter, setTypeFilter] = useState<string>('all')

  const [logs, setLogs] = useState<SystemLog[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [loading, setLoading] = useState(false)
  const [hasMore, setHasMore] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const abortControllerRef = useRef<AbortController | null>(null)

  // Initialize query sync
  useEffect(() => {
    const agentQuery = searchParams.get('agent_id')
    if (agentQuery) {
      setScope('agent')
      setSelectedAgentId(agentQuery)
    }
  }, [searchParams])

  const loadAgents = async () => {
    try {
      const data = await apiGet<Agent[]>('/agents')
      setAgents(data)
    } catch {
      // Non-blocking
    }
  }

  useEffect(() => {
    loadAgents()
  }, [])

  const loadLogs = async (reset = false, level = levelFilter, type = typeFilter) => {
    if (scope === 'agent' && !selectedAgentId) {
      setLogs([])
      setHasMore(false)
      return
    }

    abortControllerRef.current?.abort()
    const controller = new AbortController()
    abortControllerRef.current = controller

    setLoading(true)
    setError(null)
    try {
      const endpoint = scope === 'server' ? '/logs/server' : `/agents/${selectedAgentId}/logs`
      const params: Record<string, string | number | undefined> = {
        limit: 500,
        level: level === 'all' ? undefined : level,
        type: type === 'all' ? undefined : type,
      }

      if (!reset && logs.length > 0) {
        const minId = Math.min(...logs.map((l) => l.id))
        params.before_id = minId
      }

      const data = await apiGet<SystemLog[]>(endpoint, params, { signal: controller.signal })
      if (reset) {
        setLogs(data)
      } else {
        setLogs((prev) => {
          const map = new Map<number, SystemLog>()
          for (const item of [...prev, ...data]) {
            map.set(item.id, item)
          }
          return Array.from(map.values()).sort((a, b) => b.id - a.id)
        })
      }
      setHasMore(data.length >= 500)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      setError(isApiClientError(err) ? err.message : t('logs.loadFailed'))
    } finally {
      if (abortControllerRef.current === controller) {
        setLoading(false)
      }
    }
  }

  useEffect(() => {
    return () => {
      abortControllerRef.current?.abort()
    }
  }, [])

  useEffect(() => {
    loadLogs(true)
  }, [scope, selectedAgentId])

  const handleScopeChange = (nextScope: 'server' | 'agent') => {
    setScope(nextScope)
    if (nextScope === 'server') {
      searchParams.delete('agent_id')
      setSearchParams(searchParams)
    }
  }

  const handleAgentChange = (val: string) => {
    const nextAgent = val === 'none' ? '' : val
    setSelectedAgentId(nextAgent)
    if (nextAgent) {
      searchParams.set('agent_id', nextAgent)
      setSearchParams(searchParams)
    } else {
      searchParams.delete('agent_id')
      setSearchParams(searchParams)
    }
  }

  const filteredLogs = logs

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            {t('logs.title')}
          </h2>
          <p className="text-xs text-muted-foreground">
            {t('logs.subtitle')}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => loadLogs(true)}
          disabled={loading}
          className="h-8 text-xs gap-1.5 self-start sm:self-auto"
        >
          <RefreshCw className="h-3.5 w-3.5" aria-hidden="true" />
          {t('common.refresh')}
        </Button>
      </div>

      {/* Control Bar */}
      <Card className="border-border bg-card/40 shadow-sm">
        <CardContent className="p-4 flex flex-wrap items-center gap-3">
          {/* Scope Toggle */}
          <Tabs
            value={scope}
            onValueChange={(val) => handleScopeChange(val as 'server' | 'agent')}
          >
            <TabsList className="h-8 p-0.5">
              <TabsTrigger value="server" className="text-xs h-7 px-3 gap-1.5">
                <Server className="h-3.5 w-3.5" aria-hidden="true" />
                <span>{t('logs.server')}</span>
              </TabsTrigger>
              <TabsTrigger value="agent" className="text-xs h-7 px-3 gap-1.5">
                <Activity className="h-3.5 w-3.5" aria-hidden="true" />
                <span>{t('logs.agent')}</span>
              </TabsTrigger>
            </TabsList>
          </Tabs>

          {/* Agent Selector when scope === agent */}
          {scope === 'agent' && (
            <Select value={selectedAgentId || 'none'} onValueChange={handleAgentChange}>
              <SelectTrigger className="w-56 h-8 text-xs">
                <SelectValue placeholder={t('logs.agentPlaceholder')} />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="none" className="text-xs">
                  {t('logs.selectAgent')}
                </SelectItem>
                {agents.map((a) => (
                  <SelectItem key={a.id} value={a.id} className="text-xs">
                    {a.name} ({a.hostname})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          )}

          {/* Level Filter */}
          <Select value={levelFilter} onValueChange={(value) => { setLevelFilter(value); loadLogs(true, value, typeFilter) }}>
            <SelectTrigger className="w-36 h-8 text-xs">
              <SelectValue placeholder={t('logs.filters.level')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all" className="text-xs">
                {t('logs.filters.allLevels') || 'All Levels'}
              </SelectItem>
              {LOG_LEVELS.map((lvl) => (
                <SelectItem key={lvl} value={lvl} className="text-xs uppercase font-mono">
                  {lvl}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {/* Type Filter */}
          <Select value={typeFilter} onValueChange={(value) => { setTypeFilter(value); loadLogs(true, levelFilter, value) }}>
            <SelectTrigger className="w-36 h-8 text-xs">
              <SelectValue placeholder={t('logs.filters.type')} />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all" className="text-xs">
                {t('logs.filters.allTypes') || 'All Types'}
              </SelectItem>
              {LOG_TYPES.map((tp) => (
                <SelectItem key={tp} value={tp} className="text-xs">
                  {t(`logs.types.${tp}`)}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </CardContent>
      </Card>
      {scope === 'agent' && !selectedAgentId && (
        <Alert className="border-border/80 bg-muted/20 py-2.5 text-xs text-muted-foreground">
          <Info className="h-4 w-4 text-primary" />
          <AlertTitle className="text-xs font-semibold text-foreground">
            {t('logs.selectAgentHint')}
          </AlertTitle>
          <AlertDescription className="text-xs mt-0.5">
            {t('logs.selectAgentDescription') || 'Please choose an online host agent to query its event stream.'}
          </AlertDescription>
        </Alert>
      )}

      {error ? (
        <AppErrorState title={t('logs.title')} message={error} onRetry={() => loadLogs(true)} />
      ) : (
        <Card className="border-border bg-card/60 shadow-sm">
          <CardHeader className="py-3 px-4 border-b border-border flex flex-row items-center justify-between space-y-0">
            <CardTitle className="text-xs font-semibold">
              {scope === 'server' ? t('logs.serverLogs') : t('logs.agentLogs')} ({t('logs.loadedCount', { count: filteredLogs.length })})
            </CardTitle>
            {hasMore && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => loadLogs(false)}
                disabled={loading}
                className="h-7 text-xs gap-1.5"
              >
                {loading ? <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" /> : <RotateCcw className="h-3 w-3" aria-hidden="true" />}
                {t('logs.loadMore')}
              </Button>
            )}
          </CardHeader>
          <CardContent className="p-0">
            {loading && logs.length === 0 ? (
              <PageLoadingState compact />
            ) : filteredLogs.length > 0 ? (
              <div className="rounded-md overflow-hidden">
                {/* Desktop Table */}
                <div className="hidden md:block overflow-x-auto">
                  <Table className="min-w-[800px]">
                    <TableHeader>
                      <TableRow className="border-border hover:bg-transparent">
                        <TableHead className="text-xs font-medium w-16">{t('logs.columns.id')}</TableHead>
                        <TableHead className="text-xs font-medium w-24">{t('logs.columns.type')}</TableHead>
                        {scope === 'agent' && (
                          <TableHead className="text-xs font-medium w-20">{t('logs.columns.seq')}</TableHead>
                        )}
                        <TableHead className="text-xs font-medium w-44">{t('logs.columns.time')}</TableHead>
                        <TableHead className="text-xs font-medium w-20">{t('logs.columns.level')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('logs.columns.message')}</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {filteredLogs.map((item) => (
                        <TableRow key={item.id} className="border-border hover:bg-muted/30">
                          <TableCell className="text-xs font-mono text-muted-foreground py-2">
                            {item.id}
                          </TableCell>
                          <TableCell className="text-xs py-2">
                            <span className="rounded bg-muted px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground">
                              {item.type}
                            </span>
                          </TableCell>
                          {scope === 'agent' && (
                            <TableCell className="text-xs font-mono text-muted-foreground py-2">
                              {item.source_seq ?? '—'}
                            </TableCell>
                          )}
                          <TableCell className="text-xs font-mono text-muted-foreground py-2">
                            {formatDateTime(item.timestamp)}
                          </TableCell>
                          <TableCell className="text-xs py-2">
                            <StatusBadge tone={LEVEL_TONES[item.level] || 'secondary'}>
                              {item.level.toUpperCase()}
                            </StatusBadge>
                          </TableCell>
                          <TableCell className="text-xs font-mono text-foreground break-all whitespace-normal py-2">
                            {item.message}
                          </TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </div>

                {/* Mobile Cards */}
                <div className="md:hidden divide-y divide-border">
                  {filteredLogs.map((item) => (
                    <div key={item.id} className="p-3 space-y-1.5 text-xs">
                      <div className="flex items-center justify-between gap-2">
                        <span className="font-mono text-muted-foreground text-[11px]">
                          {formatDateTime(item.timestamp)}
                        </span>
                        <div className="flex items-center gap-1.5">
                          <span className="rounded bg-muted px-1.5 py-0.5 font-mono text-[11px] text-muted-foreground">
                            {item.type}
                          </span>
                          <StatusBadge tone={LEVEL_TONES[item.level] || 'secondary'}>
                            {item.level.toUpperCase()}
                          </StatusBadge>
                        </div>
                      </div>
                      {scope === 'agent' && item.source_seq != null && (
                        <div className="text-[11px] text-muted-foreground font-mono">
                          {t('logs.columns.seq')}: #{item.source_seq}
                        </div>
                      )}
                      <p className="font-mono text-foreground break-all text-xs">
                        {item.message}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="p-8">
                <AppEmptyState
                  title={t('logs.empty')}
                  description={t('logs.empty_desc')}
                />
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  )
}
