// web/src/views/settings/SettingsView.vue
<template>
  <div>
    <div class="section-title">{{ t('settings.title') }}</div>

    <el-card style="max-width: 640px">
      <template #header>
        <div style="display: flex; align-items: center; gap: 8px">
          <el-icon><Bell /></el-icon>
          <span>{{ t('settings.telegram.title') }}</span>
        </div>
      </template>

      <el-alert
        v-if="configured"
        type="success"
        :title="t('settings.telegram.configured')"
        :description="t('settings.telegram.currentTarget', { chatId })"
        show-icon
        :closable="false"
        style="margin-bottom: 16px"
      />
      <el-alert
        v-else
        type="info"
        :title="t('settings.telegram.notConfigured')"
        show-icon
        :closable="false"
        style="margin-bottom: 16px"
      />

      <el-form :model="form" label-width="110px" @submit.prevent>
        <el-form-item :label="t('settings.telegram.botToken')">
          <el-input
            v-model="form.bot_token"
            type="password"
            show-password
            :placeholder="
              configured ? t('settings.telegram.tokenPlaceholderConfigured') : '123456789:AA...'
            "
            autocomplete="new-password"
          />
        </el-form-item>
        <el-form-item :label="t('settings.telegram.chatId')">
          <el-input
            v-model="form.chat_id"
            :placeholder="configured ? chatId : '-1001234567890'"
          />
        </el-form-item>
        <el-form-item>
          <el-button type="primary" :loading="saving" @click="handleSave">
            {{ t('settings.telegram.save') }}
          </el-button>
          <el-button :loading="clearing" :disabled="!configured" @click="handleClear">
            {{ t('settings.telegram.clear') }}
          </el-button>
        </el-form-item>
      </el-form>

      <el-divider style="margin: 8px 0" />
      <div class="settings-help">
        {{ t('settings.telegram.help') }}
      </div>
    </el-card>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { apiGet, apiPut } from '@/api/client'
import type { TelegramSettings, TelegramSettingsUpdate } from '@/api/types'

const { t } = useI18n()

const configured = ref(false)
const chatId = ref('')
const saving = ref(false)
const clearing = ref(false)
const form = ref<TelegramSettingsUpdate>({ bot_token: '', chat_id: '' })

async function loadSettings(): Promise<void> {
  try {
    const settings = await apiGet<TelegramSettings>('/settings/telegram')
    configured.value = settings.configured
    chatId.value = settings.chat_id || ''
  } catch (err: any) {
    ElMessage.error(err.message || t('common.error'))
  }
}

async function handleSave(): Promise<void> {
  if (!form.value.bot_token.trim() || !form.value.chat_id.trim()) {
    ElMessage.warning(t('settings.telegram.pairRequired'))
    return
  }
  saving.value = true
  try {
    const settings = await apiPut<TelegramSettings>('/settings/telegram', {
      bot_token: form.value.bot_token.trim(),
      chat_id: form.value.chat_id.trim(),
    })
    configured.value = settings.configured
    chatId.value = settings.chat_id || ''
    form.value.bot_token = ''
    ElMessage.success(t('settings.telegram.saved'))
  } catch (err: any) {
    ElMessage.error(err.message || t('common.error'))
  } finally {
    saving.value = false
  }
}

async function handleClear(): Promise<void> {
  clearing.value = true
  try {
    await apiPut<TelegramSettings>('/settings/telegram', { bot_token: '', chat_id: '' })
    configured.value = false
    chatId.value = ''
    form.value.bot_token = ''
    form.value.chat_id = ''
    ElMessage.success(t('settings.telegram.cleared'))
  } catch (err: any) {
    ElMessage.error(err.message || t('common.error'))
  } finally {
    clearing.value = false
  }
}

onMounted(loadSettings)
</script>

<style scoped>
.settings-help {
  color: var(--el-text-color-secondary);
  font-size: 13px;
  line-height: 1.6;
}
</style>

// web/src/views/settings/SettingsView.tsx
import React, { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { apiGet, apiPut, apiDelete, isApiClientError } from '@/api/client'
import type { TelegramSettings, TelegramSettingsUpdate } from '@/api/types'
import { toastSuccess, toastError } from '@/lib/toast'
import { AppErrorState } from '@/components/AppErrorState'
import { PageLoadingState } from '@/components/PageLoadingState'
import { ConfirmActionDialog } from '@/components/ConfirmActionDialog'
import { Send, Trash2, CheckCircle2, Loader2, KeyRound, Save } from 'lucide-react'

export const SettingsView: React.FC = () => {
  const { t } = useTranslation()

  const [settings, setSettings] = useState<TelegramSettings | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [fetchError, setFetchError] = useState<string | null>(null)

  const [botToken, setBotToken] = useState('')
  const [chatId, setChatId] = useState('')
  const [validationError, setValidationError] = useState<string | null>(null)

  const [clearDialogOpen, setClearDialogOpen] = useState(false)

  const loadSettings = async () => {
    setLoading(true)
    setFetchError(null)
    try {
      const data = await apiGet<TelegramSettings>('/settings/telegram')
      setSettings(data)
      setChatId(data.chat_id || '')
      setBotToken('')
    } catch (err: unknown) {
      setFetchError(isApiClientError(err) ? err.message : t('settings.load_failed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    loadSettings()
  }, [])

  const handleSave = async (e: React.SyntheticEvent) => {
    e.preventDefault()
    setValidationError(null)

    if (!botToken.trim()) {
      setValidationError(t('validation.bot_token_required'))
      return
    }
    if (!chatId.trim()) {
      setValidationError(t('validation.chat_id_required'))
      return
    }

    setSaving(true)
    try {
      const payload: TelegramSettingsUpdate = {
        bot_token: botToken.trim(),
        chat_id: chatId.trim(),
      }
      await apiPut('/settings/telegram', payload)
      toastSuccess(t('settings.saved_success'))
      await loadSettings()
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('settings.save_failed'))
    } finally {
      setSaving(false)
    }
  }

  const handleClear = async () => {
    try {
      await apiDelete('/settings/telegram')
      toastSuccess(t('settings.cleared_success'))
      await loadSettings()
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('settings.clear_failed'))
    }
  }

  if (loading) {
    return <PageLoadingState />
  }

  if (fetchError) {
    return (
      <AppErrorState
        title={t('settings.load_failed')}
        message={fetchError}
        onRetry={loadSettings}
      />
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-bold tracking-tight text-foreground">
          {t('settings.title')}
        </h2>
        <p className="text-xs text-muted-foreground">
          {t('settings.subtitle')}
        </p>
      </div>

      <Card className="border-border bg-card/60 shadow-md">
        <CardHeader>
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-sky-500/15 text-sky-600 dark:text-sky-400">
              <Send className="h-4 w-4" aria-hidden="true" />
            </div>
            <div>
              <CardTitle className="text-sm font-semibold">
                {t('settings.telegram_title')}
              </CardTitle>
              <CardDescription className="text-xs">
                {t('settings.telegram_desc')}
              </CardDescription>
            </div>
          </div>
        </CardHeader>
        <CardContent className="space-y-6">
          {settings?.configured && (
            <div className="flex items-center justify-between rounded-md border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-600 dark:text-emerald-400 font-medium">
              <div className="flex items-center gap-2">
                <CheckCircle2 className="h-4 w-4 text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
                <span>
                  {t('settings.status_configured')}
                </span>
              </div>
              <Button
                variant="destructive"
                size="sm"
                className="h-7 text-xs"
                onClick={() => setClearDialogOpen(true)}
              >
                <Trash2 className="mr-1.5 h-3.5 w-3.5" aria-hidden="true" />
                {t('settings.clear_config')}
              </Button>
            </div>
          )}

          <form onSubmit={handleSave} className="space-y-4 max-w-lg">
            {validationError && (
              <Alert variant="destructive" className="py-2 text-xs">
                <AlertDescription>{validationError}</AlertDescription>
              </Alert>
            )}

            <div className="space-y-1.5">
              <Label htmlFor="botToken" className="text-xs flex items-center gap-1.5">
                <KeyRound className="h-3.5 w-3.5 text-muted-foreground" aria-hidden="true" />
                {t('settings.bot_token')}
              </Label>
              <Input
                id="botToken"
                type="password"
                autoComplete="new-password"
                placeholder={settings?.configured ? '••••••••••••••••' : '123456789:ABCdefGHIjklMNO...'}
                value={botToken}
                onChange={(e) => setBotToken(e.target.value)}
                disabled={saving}
                className="h-9 text-xs"
              />
              <p className="text-[11px] text-muted-foreground">
                {t('settings.bot_token_help')}
              </p>
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="chatId" className="text-xs">
                {t('settings.chat_id')}
              </Label>
              <Input
                id="chatId"
                type="text"
                placeholder="-1001234567890"
                value={chatId}
                onChange={(e) => setChatId(e.target.value)}
                disabled={saving}
                className="h-9 text-xs"
              />
              <p className="text-[11px] text-muted-foreground">
                {t('settings.chat_id_help')}
              </p>
            </div>

            <div className="flex items-center gap-2 pt-2">
              <Button type="submit" disabled={saving} className="h-9 text-xs gap-1.5">
                {saving ? (
                  <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" />
                ) : (
                  <Save className="h-3.5 w-3.5" aria-hidden="true" />
                )}
                {t('common.save')}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      <ConfirmActionDialog
        open={clearDialogOpen}
        onOpenChange={setClearDialogOpen}
        title={t('settings.clear_confirm_title')}
        description={t('settings.clear_confirm_desc')}
        destructive
        onConfirm={handleClear}
      />
    </div>
  )
}
