// web/src/views/snapshots/SnapshotsView.tsx
import React, { useEffect, useState, useMemo, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { apiGet, apiGetWithMeta, apiPost, apiDelete, isApiClientError, isAbortError } from '@/api/client'
import { KIND_LABELS } from '@/views/plans/Constants'
import type {
  Agent,
  Plan,
  Repository,
  Snapshot,
  SnapshotDeletionResponse,
  TreeEntry,
  TreeResponse,
} from '@/api/types'
import { hostPathRoots, isAbsolutePath, isWithinMappedRoot } from '@/utils/pathMapping'
import { AppErrorState } from '@/components/AppErrorState'
import type { BadgeTone } from '@/components/StatusBadge'
import { toastSuccess, toastError, toastWarning } from '@/lib/toast'
import {
  ALL_PLANS_FILTER,
  DELETED_PLANS_FILTER,
  UNASSIGNED_PLAN_FILTER,
  type BreadcrumbPart,
  type DryRunResult,
  type RestoreResponse,
  type SnapshotView,
} from './Types'
import { SnapshotFilters } from './SnapshotFilters'
import { SnapshotList } from './SnapshotList'
import { SnapshotDetailSheet } from './SnapshotDetailSheet'
import { SnapshotRestoreDialogs } from './SnapshotRestoreDialogs'

export const SnapshotsView: React.FC = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const [repos, setRepos] = useState<Repository[]>([])
  const [plans, setPlans] = useState<Plan[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [reposLoading, setReposLoading] = useState(false)
  const [mainError, setMainError] = useState<string | null>(null)
  const [selectedRepoId, setSelectedRepoId] = useState<string>('')

  const [planFilter, setPlanFilter] = useState<string>(ALL_PLANS_FILTER)
  const [snapshots, setSnapshots] = useState<Snapshot[]>([])
  const [snapshotsLoading, setSnapshotsLoading] = useState(false)
  const [snapshotsCache, setSnapshotsCache] = useState<string | null>(null)
  const [snapshotsVerifiedAt, setSnapshotsVerifiedAt] = useState<string | null>(null)

  // Drawer / Tree Explorer
  const [selectedSnapshot, setSelectedSnapshot] = useState<Snapshot | null>(null)
  const [detailDrawerOpen, setDetailDrawerOpen] = useState(false)
  const [treeLoading, setTreeLoading] = useState(false)
  const [treeEntries, setTreeEntries] = useState<TreeEntry[]>([])
  const [treePath, setTreePath] = useState('/')
  const [treeSelectedPaths, setTreeSelectedPaths] = useState<string[]>([])
  const [copiedId, setCopiedId] = useState(false)

  // Restore Modal State
  const [restoreDialogOpen, setRestoreDialogOpen] = useState(false)
  const [restoreTargetPath, setRestoreTargetPath] = useState('')
  const [overwriteMode, setOverwriteMode] = useState<'never' | 'if-changed' | 'always'>('never')
  const [selectedIncludePaths, setSelectedIncludePaths] = useState<string[]>([])
  const [dryRunLoading, setDryRunLoading] = useState(false)
  const [dryRunResult, setDryRunResult] = useState<DryRunResult | null>(null)
  const [restoreLoading, setRestoreLoading] = useState(false)

  // Restore Confirmation Prompt Dialog
  const [confirmPromptOpen, setConfirmPromptOpen] = useState(false)
  const [confirmationInput, setConfirmationInput] = useState('')

  // Delete Snapshot Prompt Dialog
  const [deletePromptOpen, setDeletePromptOpen] = useState(false)
  const [snapshotToDelete, setSnapshotToDelete] = useState<Snapshot | null>(null)
  const [deleteConfirmInput, setDeleteConfirmInput] = useState('')
  const [deletingSnapshot, setDeletingSnapshot] = useState(false)

  const snapshotsReqRef = useRef(0)
  const treeReqRef = useRef(0)
  const snapshotsAbortRef = useRef<AbortController | null>(null)
  const treeAbortRef = useRef<AbortController | null>(null)

  const selectedRepo = useMemo(
    () => repos.find((r) => r.id === selectedRepoId),
    [repos, selectedRepoId]
  )
  const selectedAgent = useMemo(
    () => agents.find((a) => a.id === selectedRepo?.agent_id),
    [agents, selectedRepo]
  )
  const restorePathMappings = useMemo(
    () => selectedAgent?.restore_path_mappings ?? [],
    [selectedAgent]
  )
  const restoreHostRoots = useMemo(
    () => hostPathRoots(restorePathMappings),
    [restorePathMappings]
  )

  const restoreTargetValidationMessage = useMemo(() => {
    const trimmed = restoreTargetPath.trim()
    if (!trimmed) return null
    if (!isAbsolutePath(trimmed)) {
      return t('snapshots.validation.absolutePathRequired')
    }
    if (!isWithinMappedRoot(trimmed, restorePathMappings)) {
      return t('snapshots.validation.pathOutsideAllowedRoots')
    }
    return null
  }, [restoreTargetPath, restoreHostRoots, t])

  const restoreTargetValid = useMemo(() => {
    const trimmed = restoreTargetPath.trim()
    return Boolean(trimmed && !restoreTargetValidationMessage)
  }, [restoreTargetPath, restoreTargetValidationMessage])

  const repositoryPlans = useMemo(() => {
    if (!selectedRepo) return []
    return plans.filter((p) => p.repository_id === selectedRepo.id)
  }, [plans, selectedRepo])

  const tagValues = (snapshot: Snapshot, prefix: string): string[] => {
    return [
      ...new Set(
        snapshot.tags
          .filter((tag) => tag.startsWith(prefix) && tag.slice(prefix.length))
          .map((tag) => tag.slice(prefix.length))
      ),
    ]
  }

  const snapshotView = (snapshot: Snapshot): SnapshotView => {
    const planIds = tagValues(snapshot, 'plan:')
    const plan = planIds.length === 1 ? plans.find((p) => p.id === planIds[0]) : undefined
    const planID = plan ? plan.id : planIds.length ? DELETED_PLANS_FILTER : UNASSIGNED_PLAN_FILTER
    const kind = tagValues(snapshot, 'kind:')[0] || plan?.kind || 'unknown'
    const known = kind in KIND_LABELS
    const runs = tagValues(snapshot, 'run:')

    let kindTone: BadgeTone = 'secondary'
    if (kind === 'filesystem') kindTone = 'default'
    else if (kind === 'sqlite') kindTone = 'outline'
    else if (known) kindTone = 'warning'

    let summary = ''
    if (plan) {
      if (plan.kind === 'filesystem') summary = plan.source.paths?.join(', ') || ''
      else if (plan.kind === 'sqlite') summary = plan.source.path || ''
      else if (plan.source.host && plan.source.database) {
        summary = `${plan.source.host}${plan.source.port ? `:${plan.source.port}` : ''}/${plan.source.database}`
      }
    }

    return {
      raw: snapshot,
      planID,
      plan,
      planName: plan?.name || (planIds.length ? t('snapshots.deletedPlan') : t('snapshots.unassignedPlan')),
      kind,
      kindLabel: known ? t(KIND_LABELS[kind as Plan['kind']]) : t('snapshots.unknownType'),
      kindTone,
      sourceSummary: summary || snapshot.paths.join(', ') || '—',
      agentDisplay: {
        name: selectedAgent?.name || 'Agent',
        hostname: selectedAgent?.hostname || snapshot.host,
      },
      runID: runs[0] || '',
      extraTags: snapshot.tags.filter(
        (tag) => !tag.startsWith('plan:') && !tag.startsWith('kind:') && !tag.startsWith('run:')
      ),
    }
  }

  const snapshotViews = useMemo(() => {
    return snapshots.map(snapshotView).sort((a, b) => Date.parse(b.raw.time) - Date.parse(a.raw.time))
  }, [snapshots, plans, selectedAgent, t])

  const filteredSnapshots = useMemo(() => {
    if (planFilter === ALL_PLANS_FILTER) return snapshotViews
    return snapshotViews.filter((s) => s.planID === planFilter)
  }, [snapshotViews, planFilter])

  const selectedSnapshotView = useMemo(() => {
    return selectedSnapshot ? snapshotView(selectedSnapshot) : null
  }, [selectedSnapshot, plans, selectedAgent, t])

  const canRestore = useMemo(() => {
    return selectedSnapshotView?.kind === 'filesystem'
  }, [selectedSnapshotView])

  const loadRepos = async () => {
    setReposLoading(true)
    setMainError(null)
    try {
      const [repoList, planList, agentList] = await Promise.all([
        apiGet<Repository[]>('/repositories'),
        apiGet<Plan[]>('/plans'),
        apiGet<Agent[]>('/agents'),
      ])
      setRepos(repoList)
      setPlans(planList)
      setAgents(agentList)
      if (!selectedRepoId && repoList.length > 0) {
        setSelectedRepoId(repoList[0].id)
      }
    } catch (err: unknown) {
      setMainError(isApiClientError(err) ? err.message : t('snapshots.messages.reposLoadFailed'))
    } finally {
      setReposLoading(false)
    }
  }

  const loadSnapshots = async (refresh = false) => {
    if (!selectedRepoId) return
    const reqId = ++snapshotsReqRef.current
    const repoId = selectedRepoId

    snapshotsAbortRef.current?.abort()
    const controller = new AbortController()
    snapshotsAbortRef.current = controller

    setSnapshotsLoading(true)
    try {
      const response = await apiGetWithMeta<Snapshot[]>(
        `/repositories/${repoId}/snapshots`,
        { refresh: refresh ? 1 : undefined },
        { signal: controller.signal }
      )
      if (reqId !== snapshotsReqRef.current || repoId !== selectedRepoId) return
      setSnapshots(response.data)
      setSnapshotsCache(response.meta.cache)
      setSnapshotsVerifiedAt(response.meta.verifiedAt)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      if (reqId !== snapshotsReqRef.current || repoId !== selectedRepoId) return
      toastError(isApiClientError(err) ? err.message : t('snapshots.messages.snapshotsLoadFailed'))
    } finally {
      if (reqId === snapshotsReqRef.current) {
        setSnapshotsLoading(false)
      }
    }
  }

  useEffect(() => {
    loadRepos()
    return () => {
      snapshotsAbortRef.current?.abort()
      treeAbortRef.current?.abort()
    }
  }, [])

  useEffect(() => {
    setPlanFilter(ALL_PLANS_FILTER)
    setSnapshots([])
    setSnapshotsCache(null)
    setSnapshotsVerifiedAt(null)
    setSelectedSnapshot(null)
    setDetailDrawerOpen(false)
    if (selectedRepoId) {
      loadSnapshots()
    }
  }, [selectedRepoId])

  const loadTree = async (path = treePath, refresh = false) => {
    if (!selectedSnapshot || !selectedRepoId) return
    const reqId = ++treeReqRef.current
    const snapshotId = selectedSnapshot.id
    const repoId = selectedRepoId

    treeAbortRef.current?.abort()
    const controller = new AbortController()
    treeAbortRef.current = controller

    setTreeLoading(true)
    try {
      const response = await apiGetWithMeta<TreeResponse>(
        `/snapshots/${snapshotId}/tree`,
        {
          repo: repoId,
          path,
          refresh: refresh ? 1 : undefined,
        },
        { signal: controller.signal }
      )
      if (reqId !== treeReqRef.current || snapshotId !== selectedSnapshot?.id || repoId !== selectedRepoId) return
      setTreeEntries(response.data.entries || [])
      setTreePath(response.data.path || path)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      if (reqId !== treeReqRef.current) return
      toastError(isApiClientError(err) ? err.message : t('snapshots.messages.treeLoadFailed'))
    } finally {
      if (reqId === treeReqRef.current) {
        setTreeLoading(false)
      }
    }
  }

  const handleSelectSnapshot = (snapshot: Snapshot) => {
    setSelectedSnapshot(snapshot)
    setDetailDrawerOpen(true)
    setTreePath('/')
    setTreeSelectedPaths([])
    setTreeEntries([])
    setDryRunResult(null)
    loadTree('/')
  }

  const navigateBreadcrumb = (path: string) => {
    setTreePath(path)
    setTreeSelectedPaths([])
    loadTree(path)
  }

  const handleNavigateDir = (nextPath: string) => {
    setTreePath(nextPath)
    setTreeSelectedPaths([])
    loadTree(nextPath)
  }

  const toggleTreeSelection = (entryName: string) => {
    const fullPath = treePath === '/' ? `/${entryName}` : `${treePath}/${entryName}`
    setTreeSelectedPaths((prev) => {
      if (prev.includes(fullPath)) {
        return prev.filter((p) => p !== fullPath)
      } else {
        return [...prev, fullPath]
      }
    })
  }

  const breadcrumbs = useMemo<BreadcrumbPart[]>(() => {
    const parts = treePath.split('/').filter(Boolean)
    const result: BreadcrumbPart[] = [{ label: '/', path: '/' }]
    let cur = ''
    for (const p of parts) {
      cur += `/${p}`
      result.push({ label: p, path: cur })
    }
    return result
  }, [treePath])

  const copySnapshotId = async () => {
    if (!selectedSnapshot) return
    try {
      await navigator.clipboard.writeText(selectedSnapshot.id)
      setCopiedId(true)
      toastSuccess(t('common.copied'))
      setTimeout(() => setCopiedId(false), 2000)
    } catch {
      toastError(t('common.copyFailed'))
    }
  }

  // Delete Snapshot
  const openDeletePrompt = (e: React.MouseEvent, snapshot: Snapshot) => {
    e.stopPropagation()
    setSnapshotToDelete(snapshot)
    setDeleteConfirmInput('')
    setDeletePromptOpen(true)
  }

  const handleDeleteSnapshotConfirm = async () => {
    if (!snapshotToDelete || !selectedRepoId) return
    if (deleteConfirmInput.trim() !== snapshotToDelete.id) {
      toastWarning(t('snapshots.delete.inputMismatch'))
      return
    }

    setDeletingSnapshot(true)
    try {
      await apiDelete<SnapshotDeletionResponse>(
        `/repositories/${selectedRepoId}/snapshots/${snapshotToDelete.id}`
      )
      toastSuccess(t('snapshots.delete.initiated'))
      setDeletePromptOpen(false)
      if (selectedSnapshot?.id === snapshotToDelete.id) {
        setDetailDrawerOpen(false)
        setSelectedSnapshot(null)
      }
      await loadSnapshots()
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('snapshots.delete.failed'))
    } finally {
      setDeletingSnapshot(false)
    }
  }

  // Restore Wizard
  const openRestoreWizard = () => {
    if (!selectedSnapshot || !canRestore) return
    setRestoreTargetPath('')
    setOverwriteMode('never')
    setSelectedIncludePaths([...treeSelectedPaths])
    setDryRunResult(null)
    setRestoreDialogOpen(true)
  }

  const handleDryRun = async () => {
    if (!selectedSnapshot || !selectedRepoId || !restoreTargetValid) return
    setDryRunLoading(true)
    setDryRunResult(null)
    try {
      const res = await apiPost<DryRunResult>('/restores/dry-run', {
        repository_id: selectedRepoId,
        snapshot_id: selectedSnapshot.id,
        include_paths: selectedIncludePaths,
        target_path: restoreTargetPath.trim(),
        overwrite_mode: overwriteMode,
      })
      setDryRunResult(res)
      toastSuccess(t('snapshots.messages.dryRunCompleted'))
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('snapshots.messages.dryRunFailed'))
    } finally {
      setDryRunLoading(false)
    }
  }

  const openConfirmPrompt = () => {
    setConfirmationInput('')
    setConfirmPromptOpen(true)
  }

  const handleExecuteRestore = async () => {
    if (!selectedSnapshot || !selectedRepoId || !dryRunResult || !restoreTargetValid) return
    if (!confirmationInput.trim()) {
      toastWarning(t('snapshots.prompt.inputRequired'))
      return
    }

    setRestoreLoading(true)
    try {
      const res = await apiPost<RestoreResponse>('/restores', {
        repository_id: selectedRepoId,
        snapshot_id: selectedSnapshot.id,
        restore_kind: 'filesystem',
        target: {
          target_path: restoreTargetPath.trim(),
          include_paths: selectedIncludePaths,
          overwrite_mode: overwriteMode,
        },
        overwrite: overwriteMode !== 'never',
        confirmation: confirmationInput.trim(),
      })
      toastSuccess(t('snapshots.messages.restoreInitiated'))
      setConfirmPromptOpen(false)
      setRestoreDialogOpen(false)
      setDetailDrawerOpen(false)
      navigate(`/runs/${res.run_id}`)
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('snapshots.messages.restoreFailed'))
    } finally {
      setRestoreLoading(false)
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            {t('snapshots.title')}
          </h2>
          <p className="text-xs text-muted-foreground">
            {t('snapshots.subtitle')}
          </p>
        </div>
      </div>

      {mainError ? (
        <AppErrorState title={t('snapshots.title')} message={mainError} onRetry={loadRepos} />
      ) : (
        <div className="space-y-4">
          <SnapshotFilters
            repos={repos}
            selectedRepoId={selectedRepoId}
            onSelectRepo={setSelectedRepoId}
            reposLoading={reposLoading}
            planFilter={planFilter}
            onSelectPlanFilter={setPlanFilter}
            repositoryPlans={repositoryPlans}
            snapshotsCache={snapshotsCache}
            snapshotsVerifiedAt={snapshotsVerifiedAt}
            snapshotsCount={filteredSnapshots.length}
            snapshotsLoading={snapshotsLoading}
            onRefresh={() => loadSnapshots(true)}
          />

          <SnapshotList
            selectedRepoId={selectedRepoId}
            snapshotsLoading={snapshotsLoading}
            totalSnapshots={snapshots.length}
            filteredSnapshots={filteredSnapshots}
            onSelectSnapshot={handleSelectSnapshot}
            onDeleteSnapshot={openDeletePrompt}
          />
        </div>
      )}

      <SnapshotDetailSheet
        open={detailDrawerOpen}
        onOpenChange={setDetailDrawerOpen}
        selectedSnapshotView={selectedSnapshotView}
        canRestore={canRestore}
        copiedId={copiedId}
        treeLoading={treeLoading}
        treeEntries={treeEntries}
        treePath={treePath}
        breadcrumbs={breadcrumbs}
        treeSelectedPaths={treeSelectedPaths}
        onViewRun={(runId) => navigate(`/runs/${runId}`)}
        onOpenRestore={openRestoreWizard}
        onCopySnapshotId={copySnapshotId}
        onNavigateBreadcrumb={navigateBreadcrumb}
        onNavigateDir={handleNavigateDir}
        onToggleTreeSelection={toggleTreeSelection}
      />

      <SnapshotRestoreDialogs
        restoreDialogOpen={restoreDialogOpen}
        onRestoreDialogOpenChange={setRestoreDialogOpen}
        restoreTargetPath={restoreTargetPath}
        onRestoreTargetPathChange={(val) => {
          setRestoreTargetPath(val)
          setDryRunResult(null)
        }}
        restoreTargetValidationMessage={restoreTargetValidationMessage}
        restoreHostRoots={restoreHostRoots}
        overwriteMode={overwriteMode}
        onOverwriteModeChange={setOverwriteMode}
        selectedIncludePaths={selectedIncludePaths}
        dryRunResult={dryRunResult}
        dryRunLoading={dryRunLoading}
        restoreTargetValid={restoreTargetValid}
        restoreLoading={restoreLoading}
        onDryRun={handleDryRun}
        onOpenConfirmPrompt={openConfirmPrompt}
        confirmPromptOpen={confirmPromptOpen}
        onConfirmPromptOpenChange={setConfirmPromptOpen}
        selectedSnapshot={selectedSnapshot}
        confirmationInput={confirmationInput}
        onConfirmationInputChange={setConfirmationInput}
        onExecuteRestore={handleExecuteRestore}
        deletePromptOpen={deletePromptOpen}
        onDeletePromptOpenChange={setDeletePromptOpen}
        snapshotToDelete={snapshotToDelete}
        deleteConfirmInput={deleteConfirmInput}
        onDeleteConfirmInputChange={setDeleteConfirmInput}
        deletingSnapshot={deletingSnapshot}
        onDeleteConfirm={handleDeleteSnapshotConfirm}
      />
    </div>
  )
}

// web/src/views/snapshots/SnapshotsView.vue
<template>
  <div>
    <div class="section-title">{{ t('snapshots.title') }}</div>

    <div v-if="mainError" class="error-state">
      <el-icon><Warning /></el-icon>
      <p>{{ mainError }}</p>
      <el-button type="primary" @click="loadRepos" style="margin-top: 12px">{{ t('common.retry') }}</el-button>
    </div>

    <el-card v-else shadow="never" style="margin-bottom: 16px">
      <template #header>
        <span style="font-weight: 600">{{ t('snapshots.selectRepository') }}</span>
      </template>
      <el-select
        v-model="selectedRepoId"
        :placeholder="t('snapshots.repositoryPlaceholder')"
        style="width: 100%"
        :loading="reposLoading"
        :disabled="reposLoading"
        filterable
      >
        <el-option
          v-for="r in repos"
          :key="r.id"
          :label="`${r.agent_name || r.agent_id} / ${r.storage_target_name || r.storage_target_id} / ${r.repository_path}`"
          :value="r.id"
        />
      </el-select>
    </el-card>

    <el-row :gutter="16" v-if="selectedRepoId">
      <el-col :span="16">
        <el-card shadow="never">
          <template #header>
            <div style="display: flex; align-items: center; gap: 8px">
              <span style="font-weight: 600">{{ t('snapshots.snapshotsCard') }}</span>
              <el-select v-model="planFilter" :placeholder="t('snapshots.planFilter.label')" style="width: 180px">
                <el-option :label="t('snapshots.planFilter.all')" :value="ALL_PLANS_FILTER" />
                <el-option v-for="plan in repositoryPlans" :key="plan.id" :label="plan.name" :value="plan.id" />
                <el-option :label="t('snapshots.planFilter.deleted')" :value="DELETED_PLANS_FILTER" />
                <el-option :label="t('snapshots.planFilter.unassigned')" :value="UNASSIGNED_PLAN_FILTER" />
              </el-select>
              <el-text v-if="snapshotsCacheLabel" size="small" type="info">{{ snapshotsCacheLabel }}</el-text>
              <el-button size="small" :loading="snapshotsLoading" @click="loadSnapshots(true)">
                <el-icon><Refresh /></el-icon>
                <span>{{ t('snapshots.refresh') }}</span>
              </el-button>
            </div>
          </template>

          <div v-if="snapshotsLoading" style="text-align: center; padding: 16px">
            <el-icon class="is-loading"><Loading /></el-icon>
          </div>

          <el-table
            v-else
            :data="filteredSnapshots"
            stripe
            size="small"
            @row-click="handleSelectSnapshot"
            :row-class-name="({ row }) => selectedSnapshot?.id === row.id ? 'selected-row' : ''"
            style="width: 100%; cursor: pointer"
            height="520"
          >
            <el-table-column :label="t('snapshots.browseTable.id')" width="80">
              <template #default="{ row }">
                <code style="font-size: 12px">{{ shortId(row.id) }}</code>
              </template>
            </el-table-column>
            <el-table-column :label="t('snapshots.browseTable.time')" width="150">
              <template #default="{ row }">
                <span style="font-size: 12px">{{ formatTime(row.time) }}</span>
              </template>
            </el-table-column>
            <el-table-column :label="t('snapshots.browseTable.host')" width="100">
              <template #default="{ row }">
                <span style="font-size: 12px">{{ row.host }}</span>
              </template>
            </el-table-column>
            <el-table-column :label="t('snapshots.browseTable.tags')">
              <template #default="{ row }">
                <el-tag
                  v-for="tag in row.tags.slice(0, 3)"
                  :key="tag"
                  size="small"
                  effect="plain"
                  style="margin-right: 2px; margin-bottom: 2px"
                >
                  {{ tag }}
                </el-tag>
                <el-text v-if="row.tags.length > 3" size="small" color="info">
                  +{{ row.tags.length - 3 }}
                </el-text>
              </template>
            </el-table-column>
            <el-table-column :label="t('snapshots.browseTable.paths')">
              <template #default="{ row }">
                <el-tag
                  v-for="p in row.paths.slice(0, 3)"
                  :key="p"
                  size="small"
                  type="info"
                  effect="plain"
                  style="margin-right: 2px; margin-bottom: 2px"
                >
                  {{ p }}
                </el-tag>
                <el-text v-if="row.paths.length > 3" size="small" color="info">
                  +{{ row.paths.length - 3 }}
                </el-text>
              </template>
            </el-table-column>
            <el-table-column :label="t('common.actions')" width="80" fixed="right">
              <template #default="{ row }">
                <el-button type="danger" link size="small" @click.stop="handleDeleteSnapshot(row as Snapshot)">
                  {{ t('snapshots.delete.action') }}
                </el-button>
              </template>
            </el-table-column>
          </el-table>

          <el-empty v-if="!snapshotsLoading && filteredSnapshots.length === 0" :description="t('snapshots.noSnapshots')" :image-size="40" />
        </el-card>
      </el-col>

      <el-col :span="8">
        <el-card shadow="never" style="height: 580px; display: flex; flex-direction: column">
          <template #header>
            <div style="display: flex; justify-content: space-between; align-items: center">
              <div>
                <span style="font-weight: 600">{{ t('snapshots.fileBrowser') }}</span>
                <span v-if="selectedSnapshot" style="font-size: 12px; color: #909399; margin-left: 8px">
                  {{ t('snapshots.snapshotPrefix', { id: shortId(selectedSnapshot.id) }) }}
                </span>
                <el-text v-if="treeCacheLabel" size="small" type="info" style="margin-left: 8px">{{ treeCacheLabel }}</el-text>
              </div>
              <div>
                <el-button
                  v-if="selectedSnapshot"
                  size="small"
                  :loading="treeLoading"
                  @click="loadTree(true)"
                >
                  <el-icon><Refresh /></el-icon>
                  <span>{{ t('snapshots.refresh') }}</span>
                </el-button>
                <el-button
                  v-if="selectedSnapshot"
                  size="small"
                  type="primary"
                  @click="openRestoreWizard"
                  :disabled="treeLoading || !treePath"
                >
                  <el-icon><Download /></el-icon>
                  <span>{{ t('snapshots.restoreThisSnapshot') }}</span>
                </el-button>
              </div>
            </div>
          </template>

          <div v-if="!selectedSnapshot" style="flex: 1; display: flex; align-items: center; justify-content: center">
            <el-empty :description="t('snapshots.selectSnapshotHint')" />
          </div>

          <div v-else style="flex: 1; display: flex; flex-direction: column">
            <!-- Breadcrumb -->
            <el-breadcrumb separator="/" style="margin-bottom: 8px; padding: 4px 0">
              <el-breadcrumb-item
                v-for="part in breadcrumbs"
                :key="part.path"
                style="cursor: pointer"
                @click="navigateBreadcrumb(part.path)"
              >
                {{ part.label }}
              </el-breadcrumb-item>
            </el-breadcrumb>

            <div v-if="treeLoading" style="text-align: center; padding: 16px">
              <el-icon class="is-loading"><Loading /></el-icon>
            </div>

            <el-table
              v-else
              :data="treeEntries"
              stripe
              size="small"
              row-key="name"
              style="flex: 1"
              @selection-change="handleTreeSelection"
            >
              <el-table-column type="selection" width="40" />
              <el-table-column :label="t('common.name')">
                <template #default="{ row }">
                  <span style="cursor: pointer" :style="{ color: row.type === 'dir' ? '#e6a23c' : 'inherit' }" @click="handleRowClick(row as TreeEntry)">
                    <el-icon v-if="row.type === 'dir'" style="color: #e6a23c"><Folder /></el-icon>
                    <el-icon v-else><Document /></el-icon>
                    {{ row.name }}
                  </span>
                </template>
              </el-table-column>
              <el-table-column :label="t('snapshots.browseTable.type')" width="60">
                <template #default="{ row }">
                  <el-tag :type="row.type === 'dir' ? 'warning' : 'info'" size="small">{{ entryTypeText(row.type) }}</el-tag>
                </template>
              </el-table-column>
              <el-table-column :label="t('snapshots.browseTable.size')" width="120">
                <template #default="{ row }">
                  {{ formatSize(row.size) }}
                </template>
              </el-table-column>
              <el-table-column :label="t('snapshots.browseTable.modified')">
                <template #default="{ row }">
                  {{ formatTime(row.mtime) }}
                </template>
              </el-table-column>
            </el-table>
          </div>
        </el-card>
      </el-col>
    </el-row>

    <!-- Restore wizard dialog -->
    <el-dialog
      v-model="restoreDialogVisible"
      :title="t('snapshots.restoreDialog.title')"
      width="680"
      destroy-on-close
      :close-on-click-modal="false"
    >
      <el-form :model="restoreForm" label-position="top" label-width="130px">
        <el-form-item :label="t('snapshots.restoreDialog.snapshot')" required>
          <el-text>
            <code>{{ selectedSnapshot?.id }}</code>
            &nbsp;
            <span style="color: #909399">({{ formatTime(selectedSnapshot?.time || '') }})</span>
          </el-text>
        </el-form-item>

        <el-form-item :label="t('snapshots.restoreDialog.targetPath')" required>
          <el-input
            v-model="restoreForm.target_path"
            placeholder="/absolute/path/on/agent"
          />
          <el-text size="small" color="info">{{ t('snapshots.restoreDialog.targetPathHint') }}</el-text>
        </el-form-item>

        <el-form-item :label="t('snapshots.restoreDialog.overwriteMode')" required>
          <el-radio-group v-model="restoreForm.overwrite_mode">
            <el-radio value="never">{{ t('snapshots.restoreDialog.never') }}</el-radio>
            <el-radio value="if-changed">{{ t('snapshots.restoreDialog.ifChanged') }}</el-radio>
            <el-radio value="always">{{ t('snapshots.restoreDialog.always') }}</el-radio>
          </el-radio-group>
        </el-form-item>

        <el-form-item :label="t('snapshots.restoreDialog.includePaths')">
          <el-checkbox-group v-model="restoreForm.include_paths">
            <div style="display: flex; flex-direction: column; gap: 4px; max-height: 200px; overflow-y: auto">
              <el-checkbox
                v-for="p in includePathOptions"
                :key="p"
                :value="p"
                style="margin-left: 0"
              >
                {{ p }}
              </el-checkbox>
              <el-checkbox
                v-if="treeEntries.length > 0 && includePathOptions.length < treeEntries.length"
                :value="'/ (all entries in current directory)'"
                style="margin-left: 0"
              >
                {{ t('snapshots.restoreDialog.allEntries') }}
              </el-checkbox>
            </div>
          </el-checkbox-group>
          <el-text size="small" color="info">
            {{ t('snapshots.restoreDialog.includePathsHint') }}
          </el-text>
        </el-form-item>
      </el-form>

      <el-divider />

      <div v-if="dryRunResult" style="margin-top: 12px">
        <el-alert :title="t('snapshots.restoreDialog.dryRunResult')" type="success" :closable="false">
          <template #default>
            <div style="display: flex; gap: 16px; margin-top: 8px; flex-wrap: wrap">
              <el-statistic :title="t('snapshots.restoreDialog.add')" :value="dryRunResult.add" />
              <el-statistic :title="t('snapshots.restoreDialog.changed')" :value="dryRunResult.changed" />
              <el-statistic :title="t('snapshots.restoreDialog.skipped')" :value="dryRunResult.skipped" />
              <el-statistic :title="t('snapshots.restoreDialog.deleteStat')" :value="dryRunResult.delete" />
            </div>
            <div v-if="dryRunResult.sample && dryRunResult.sample.length > 0" style="margin-top: 8px">
              <el-text size="small" style="font-weight: 600">{{ t('snapshots.restoreDialog.sampleChanges') }}</el-text>
              <el-tag
                v-for="s in dryRunResult.sample.slice(0, 10)"
                :key="s"
                size="small"
                type="info"
                effect="plain"
                style="margin-right: 4px; margin-top: 4px"
              >
                {{ s }}
              </el-tag>
              <el-text v-if="dryRunResult.sample.length > 10" size="small" color="info">
                {{ t('snapshots.restoreDialog.moreChanges', { count: dryRunResult.sample.length - 10 }) }}
              </el-text>
            </div>
          </template>
        </el-alert>
      </div>

      <template #footer>
        <el-button @click="restoreDialogVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button
          type="info"
          @click="handleDryRun"
          :loading="dryRunLoading"
          :disabled="!restoreForm.target_path"
        >
          <el-icon><Search /></el-icon>
          <span>{{ t('snapshots.restoreDialog.dryRunButton') }}</span>
        </el-button>
        <el-button
          type="primary"
          @click="handleConfirmRestore"
          :loading="restoreLoading"
          :disabled="!restoreForm.target_path || !dryRunResult"
        >
          <span>{{ t('snapshots.restoreDialog.confirmExecute') }}</span>
        </el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { apiDelete, apiGet, apiGetWithMeta, apiPost } from '@/api/client'
import { ElMessage, ElMessageBox } from 'element-plus'
import { formatDateTime } from '@/i18n'
import type { Plan, Repository, Snapshot, SnapshotDeletionResponse, TreeEntry, TreeResponse } from '@/api/types'

const { t } = useI18n()

function entryTypeText(type: string): string {
  return t(`snapshots.fileTypes.${type}`)
}

// Local types
interface DryRunResult {
  add: number
  changed: number
  skipped: number
  delete: number
  sample: string[]
}

interface RestoreResponse {
  restore_request_id: string
  run_id: string
}

interface BreadcrumbPart {
  label: string
  path: string
}

const repos = ref<Repository[]>([])
const reposLoading = ref(false)
const mainError = ref('')
const router = useRouter()

const selectedRepoId = ref<string>('')

const ALL_PLANS_FILTER = 'all'
const DELETED_PLANS_FILTER = 'deleted'
const UNASSIGNED_PLAN_FILTER = 'unassigned'
type PlanFilter = typeof ALL_PLANS_FILTER | typeof DELETED_PLANS_FILTER | typeof UNASSIGNED_PLAN_FILTER | string

const plans = ref<Plan[]>([])
const planFilter = ref<PlanFilter>(ALL_PLANS_FILTER)
const snapshots = ref<Snapshot[]>([])
const snapshotsLoading = ref(false)
const snapshotsCache = ref<string | null>(null)
const snapshotsVerifiedAt = ref<string | null>(null)

const selectedSnapshot = ref<Snapshot | null>(null)
const treeLoading = ref(false)
const treeCache = ref<string | null>(null)
const treeVerifiedAt = ref<string | null>(null)
const treeEntries = ref<TreeEntry[]>([])
const treePath = ref('/')
const treeSelectedPaths = ref<string[]>([])

const restoreDialogVisible = ref(false)
const restoreForm = ref({
  target_path: '',
  overwrite_mode: 'never' as 'never' | 'if-changed' | 'always',
  include_paths: [] as string[],
})
const dryRunLoading = ref(false)
const dryRunResult = ref<DryRunResult | null>(null)
const restoreLoading = ref(false)

const breadcrumbs = computed<BreadcrumbPart[]>(() => {
  const p = treePath.value
  if (p === '/' || p === '') return [{ label: '/', path: '/' }]
  const parts = p.split('/').filter(Boolean)
  const result: BreadcrumbPart[] = [{ label: '/', path: '/' }]
  let acc = ''
  for (const part of parts) {
    acc += '/' + part
    result.push({ label: part, path: acc })
  }
  return result
})
const snapshotsCacheLabel = computed(() => formatCacheLabel(snapshotsCache.value, snapshotsVerifiedAt.value))
const treeCacheLabel = computed(() => formatCacheLabel(treeCache.value, treeVerifiedAt.value))

const repositoryPlans = computed(() => plans.value.filter((plan) => plan.repository_id === selectedRepoId.value))
const filteredSnapshots = computed(() => {
  if (planFilter.value === ALL_PLANS_FILTER) return snapshots.value

  const currentPlanIDs = new Set(plans.value.map((plan) => plan.id))
  return snapshots.value.filter((snapshot) => {
    const planIDs = snapshot.tags
      .filter((tag) => tag.startsWith('plan:'))
      .map((tag) => tag.slice('plan:'.length))

    if (planFilter.value === UNASSIGNED_PLAN_FILTER) return planIDs.length === 0
    if (planFilter.value === DELETED_PLANS_FILTER) {
      return planIDs.length > 0 && planIDs.every((planID) => !currentPlanIDs.has(planID))
    }
    return planIDs.includes(planFilter.value)
  })
})

function formatCacheLabel(cache: string | null, verifiedAt: string | null): string {
  if (!cache) return ''
  const status = cache === 'HIT' ? t('snapshots.cache.hit') : t('snapshots.cache.miss')
  const verified = verifiedAt ? formatTime(verifiedAt) : t('snapshots.cache.unknownTime')
  return t('snapshots.cache.status', { status, time: verified })
}

const includePathOptions = computed<string[]>(() => {
  return treeEntries.value
    .filter((e) => e.type === 'file' || e.type === 'dir')
    .map((e) => treePath.value === '/' ? '/' + e.name : treePath.value + '/' + e.name)
})

function shortId(id: string | undefined): string {
  if (!id) return ''
  return id.length > 8 ? id.slice(0, 8) : id
}

function formatTime(iso: string): string {
  return formatDateTime(iso)
}

function formatSize(bytes: number): string {
  if (bytes <= 0) return '-'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  if (i === 0) return `${bytes} B`
  return `${(bytes / Math.pow(1024, i)).toFixed(1)} ${units[i]}`
}

async function loadRepos(): Promise<void> {
  reposLoading.value = true
  mainError.value = ''
  try {
    const [repositoryList, planList] = await Promise.all([
      apiGet<Repository[]>('/repositories'),
      apiGet<Plan[]>('/plans'),
    ])
    repos.value = repositoryList
    plans.value = planList
    // Pre-select the first repo
    if (repos.value.length > 0 && !selectedRepoId.value) {
      selectedRepoId.value = repos.value[0].id
    }
  } catch (err: unknown) {
    const e = err as { message?: string }
    mainError.value = e.message || t('snapshots.messages.reposLoadFailed')
  } finally {
    reposLoading.value = false
  }
}

async function loadSnapshots(refresh = false): Promise<void> {
  if (!selectedRepoId.value) return
  snapshotsLoading.value = true
  clearSnapshotSelection()
  try {
    const response = await apiGetWithMeta<Snapshot[]>(`/repositories/${selectedRepoId.value}/snapshots`, {
      refresh: refresh ? 1 : undefined,
    })
    snapshots.value = response.data
    snapshotsCache.value = response.meta.cache
    snapshotsVerifiedAt.value = response.meta.verifiedAt
  } catch (err: unknown) {
    const e = err as { message?: string; code?: string }
    ElMessage.error(e.message || t('snapshots.messages.loadSnapshotsFailedCode', { code: e.code || 'unknown' }))
    snapshots.value = []
    snapshotsCache.value = null
    snapshotsVerifiedAt.value = null
  } finally {
    snapshotsLoading.value = false
  }
}

function clearSnapshotSelection(): void {
  selectedSnapshot.value = null
  treeEntries.value = []
  treePath.value = '/'
  treeSelectedPaths.value = []
  treeCache.value = null
  treeVerifiedAt.value = null
  restoreDialogVisible.value = false
  dryRunResult.value = null
}

async function handleDeleteSnapshot(snapshot: Snapshot): Promise<void> {
  if (!selectedRepoId.value) return
  try {
    const { value } = await ElMessageBox.prompt(
      t('snapshots.delete.message'),
      t('snapshots.delete.title'),
      {
        confirmButtonText: t('snapshots.delete.confirm'),
        cancelButtonText: t('common.cancel'),
        inputPlaceholder: t('snapshots.delete.inputPlaceholder'),
        inputValidator: (value) => value === snapshot.id || t('snapshots.delete.inputMismatch'),
      },
    )
    if (value !== snapshot.id) return

    await apiDelete<SnapshotDeletionResponse>(`/repositories/${selectedRepoId.value}/snapshots/${snapshot.id}`)
    snapshots.value = snapshots.value.filter((item) => item.id !== snapshot.id)
    if (selectedSnapshot.value?.id === snapshot.id) clearSnapshotSelection()
    ElMessage.success(t('snapshots.messages.deleteQueued'))
  } catch (err: unknown) {
    if (err === 'cancel') return
    const e = err as { message?: string; status?: number }
    if (e.status === 409) {
      ElMessage.warning(t('snapshots.messages.deleteRefreshRequired'))
      await loadSnapshots(true)
      return
    }
    ElMessage.error(e.message || t('snapshots.messages.deleteFailed'))
  }
}

async function handleSelectSnapshot(snapshot: Snapshot): Promise<void> {
  selectedSnapshot.value = snapshot
  treePath.value = '/'
  treeSelectedPaths.value = []
  await loadTree()
}

async function loadTree(refresh = false): Promise<void> {
  if (!selectedSnapshot.value || !selectedRepoId.value) return
  treeLoading.value = true
  try {
    const response = await apiGetWithMeta<TreeResponse>('/snapshots/' + selectedSnapshot.value.id + '/tree', {
      repo: selectedRepoId.value,
      path: treePath.value,
      refresh: refresh ? 1 : undefined,
    })
    treeEntries.value = response.data.entries || []
    treePath.value = response.data.path || treePath.value
    treeCache.value = response.meta.cache
    treeVerifiedAt.value = response.meta.verifiedAt
  } catch (err: unknown) {
    const e = err as { message?: string; code?: string }
    ElMessage.error(e.message || t('snapshots.messages.loadTreeFailedCode', { code: e.code || 'unknown' }))
    treeCache.value = null
    treeVerifiedAt.value = null
  } finally {
    treeLoading.value = false
  }
}

function handleRowClick(entry: TreeEntry): void {
  if (entry.type !== 'dir') return
  const newPath = treePath.value === '/' ? '/' + entry.name : treePath.value + '/' + entry.name
  treePath.value = newPath
  treeSelectedPaths.value = []
  loadTree()
}

function navigateBreadcrumb(path: string): void {
  treePath.value = path
  treeSelectedPaths.value = []
  loadTree()
}

function handleTreeSelection(rows: TreeEntry[]): void {
  treeSelectedPaths.value = rows.map((r) => {
    const parent = treePath.value === '/' ? '/' : treePath.value
    return parent + '/' + r.name
  })
}

function openRestoreWizard(): void {
  if (!selectedSnapshot.value) return
  restoreForm.value = {
    target_path: '',
    overwrite_mode: 'never',
    include_paths: [...treeSelectedPaths.value],
  }
  dryRunResult.value = null
  restoreDialogVisible.value = true
}

async function handleDryRun(): Promise<void> {
  if (!selectedSnapshot.value || !selectedRepoId.value) return
  dryRunLoading.value = true
  dryRunResult.value = null
  try {
    dryRunResult.value = await apiPost<DryRunResult>('/restores/dry-run', {
      repository_id: selectedRepoId.value,
      snapshot_id: selectedSnapshot.value.id,
      include_paths: restoreForm.value.include_paths,
      target_path: restoreForm.value.target_path,
      overwrite_mode: restoreForm.value.overwrite_mode,
    })
    ElMessage.success(t('snapshots.messages.dryRunCompleted'))
  } catch (err: unknown) {
    const e = err as { message?: string; code?: string }
    ElMessage.error(e.message || t('snapshots.messages.dryRunFailedCode', { code: e.code || 'unknown' }))
  } finally {
    dryRunLoading.value = false
  }
}

async function handleConfirmRestore(): Promise<void> {
  if (!selectedSnapshot.value || !selectedRepoId.value || !dryRunResult.value) return
  try {
    const { value } = await ElMessageBox.prompt(
      t('snapshots.prompt.message'),
      t('snapshots.prompt.title'),
      {
        confirmButtonText: t('snapshots.prompt.execute'),
        cancelButtonText: t('common.cancel'),
        inputPlaceholder: t('snapshots.prompt.inputPlaceholder', { example: shortId(selectedSnapshot.value.id) }),
        inputPattern: /.+/,
        inputErrorMessage: t('snapshots.prompt.inputRequired'),
      },
    )
    if (!value) return

    restoreLoading.value = true
    const resp = await apiPost<RestoreResponse>('/restores', {
      repository_id: selectedRepoId.value,
      snapshot_id: selectedSnapshot.value.id,
      restore_kind: 'filesystem',
      target: {
        target_path: restoreForm.value.target_path,
        include_paths: restoreForm.value.include_paths,
        overwrite_mode: restoreForm.value.overwrite_mode,
      },
      overwrite: restoreForm.value.overwrite_mode !== 'never',
      confirmation: value,
    })

    ElMessage.success(t('snapshots.messages.restoreInitiated'))
    restoreDialogVisible.value = false
    router.push(`/runs/${resp.run_id}`)
  } catch (err: unknown) {
    if (err === 'cancel') return
    const e = err as { message?: string; code?: string }
    ElMessage.error(e.message || t('snapshots.messages.restoreFailedCode', { code: e.code || 'unknown' }))
  } finally {
    restoreLoading.value = false
  }
}

watch(selectedRepoId, (newId) => {
  planFilter.value = ALL_PLANS_FILTER
  clearSnapshotSelection()
  if (newId) {
    loadSnapshots()
  } else {
    snapshots.value = []
  }
})

watch(planFilter, () => {
  clearSnapshotSelection()
})

loadRepos()
</script>
