// web/src/views/runs/RunDetailView.tsx
import React, { useEffect, useState, useRef, useMemo } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Progress } from '@/components/ui/progress'
import { apiGet, isApiClientError, isAbortError } from '@/api/client'
import { formatDateTime, translateEnum } from '@/i18n'
import type { Run, RunProgress, RunLog, Plan, Agent } from '@/api/types'
import { AppErrorState } from '@/components/AppErrorState'
import { StatusBadge } from '@/components/StatusBadge'
import { PageLoadingState } from '@/components/PageLoadingState'
import { toastSuccess, toastError } from '@/lib/toast'
import {
  statusTagType,
  operationTagType,
  formatBytes,
  formatDuration,
} from '@/utils/runDisplay'
import {
  ArrowLeft,
  Copy,
  Check,
  Radio,
  Terminal,
  RotateCcw,
  Loader2,
  FileText,
} from 'lucide-react'

interface WsStateMessage {
  type: 'state'
  run: Run
}

interface WsProgressMessage {
  type: 'progress'
  progress: RunProgress
}

interface WsLogMessage {
  type: 'log'
  entry: RunLog
}

type WsMessage = WsStateMessage | WsProgressMessage | WsLogMessage

const MAX_LOG_ROWS = 5000
const MAX_RECONNECT = 5

function isTerminal(status?: string): boolean {
  return status === 'succeeded' || status === 'failed' || status === 'cancelled'
}

export const RunDetailView: React.FC = () => {
  const { id } = useParams<{ id: string }>()
  const { t } = useTranslation()
  const navigate = useNavigate()

  const [run, setRun] = useState<Run | null>(null)
  const [plans, setPlans] = useState<Plan[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [logs, setLogs] = useState<RunLog[]>([])

  const [loading, setLoading] = useState(true)
  const [loadingLogs, setLoadingLogs] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [hasMoreLogs, setHasMoreLogs] = useState(false)
  const [autoScroll, setAutoScroll] = useState(true)

  const [wsConnected, setWsConnected] = useState(false)
  const [copiedSnapshot, setCopiedSnapshot] = useState(false)

  const logsWrapRef = useRef<HTMLDivElement | null>(null)
  const wsRef = useRef<WebSocket | null>(null)
  const reconnectCountRef = useRef(0)
  const terminalRef = useRef(false)
  const reconnectTimerRef = useRef<number | null>(null)
  const logsAbortControllerRef = useRef<AbortController | null>(null)

  const loadRun = async () => {
    if (!id) return
    setLoading(true)
    setError(null)
    try {
      const data = await apiGet<Run>(`/runs/${id}`)
      setRun(data)
      terminalRef.current = isTerminal(data.status)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      setError(isApiClientError(err) ? err.message : t('runDetail.loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  const loadPlansAndAgents = async () => {
    try {
      const [planList, agentList] = await Promise.all([
        apiGet<Plan[]>('/plans'),
        apiGet<Agent[]>('/agents'),
      ])
      setPlans(planList)
      setAgents(agentList)
    } catch {
      // Non-critical
    }
  }

  const loadInitialLogs = async () => {
    if (!id) return
    setLoadingLogs(true)
    logsAbortControllerRef.current?.abort()
    const controller = new AbortController()
    logsAbortControllerRef.current = controller
    try {
      const data = await apiGet<RunLog[]>(`/runs/${id}/logs`, { limit: 500 }, { signal: controller.signal })
      setLogs(data)
      setHasMoreLogs(data.length >= 500)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      // Non-critical
    } finally {
      if (logsAbortControllerRef.current === controller) {
        setLoadingLogs(false)
      }
    }
  }

  const loadMoreLogs = async () => {
    if (!id || logs.length === 0 || loadingLogs) return
    setLoadingLogs(true)
    try {
      const minSeq = Math.min(...logs.map((l) => l.seq))
      const beforeSeq = minSeq - 1
      if (beforeSeq <= 0) {
        setHasMoreLogs(false)
        return
      }
      const data = await apiGet<RunLog[]>(`/runs/${id}/logs`, {
        before_seq: beforeSeq,
        limit: 500,
      })
      if (data.length < 500) {
        setHasMoreLogs(false)
      }
      setLogs((prev) => {
        const merged = [...data, ...prev]
        const seqMap = new Map<number, RunLog>()
        for (const item of merged) {
          seqMap.set(item.seq, item)
        }
        const unique = Array.from(seqMap.values()).sort((a, b) => a.seq - b.seq)
        if (unique.length > MAX_LOG_ROWS) {
          unique.splice(0, unique.length - MAX_LOG_ROWS)
        }
        return unique
      })
    } catch {
      // Non-critical
    } finally {
      setLoadingLogs(false)
    }
  }

  // Handle Log Auto-scroll
  useEffect(() => {
    if (autoScroll && logsWrapRef.current) {
      logsWrapRef.current.scrollTop = logsWrapRef.current.scrollHeight
    }
  }, [logs, autoScroll])

  // WebSocket lifecycle
  useEffect(() => {
    if (!id || id === 'undefined' || id === 'null') return

    loadRun()
    loadPlansAndAgents()
    loadInitialLogs()

    let active = true

    const connectWs = () => {
      if (!active) return
      if (wsRef.current) {
        wsRef.current.close()
        wsRef.current = null
      }

      const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:'
      const url = `${protocol}//${window.location.host}/ws/runs/${encodeURIComponent(id)}`

      try {
        const socket = new WebSocket(url)
        wsRef.current = socket

        socket.onopen = () => {
          if (!active) return
          reconnectCountRef.current = 0
          setWsConnected(true)
        }

        socket.onmessage = (event) => {
          if (!active) return
          try {
            const msg = JSON.parse(event.data) as WsMessage
            if (msg.type === 'state') {
              setRun(msg.run)
              terminalRef.current = isTerminal(msg.run.status)
              if (terminalRef.current) {
                if (reconnectTimerRef.current) {
                  clearTimeout(reconnectTimerRef.current)
                  reconnectTimerRef.current = null
                }
                socket.close()
              }
            } else if (msg.type === 'progress') {
              setRun((prev) => (prev ? { ...prev, progress: msg.progress } : prev))
            } else if (msg.type === 'log') {
              setLogs((prev) => {
                const idx = prev.findIndex((l) => l.seq === msg.entry.seq)
                if (idx >= 0) {
                  const updated = [...prev]
                  updated[idx] = msg.entry
                  return updated
                }
                const next = [...prev, msg.entry]
                if (next.length > MAX_LOG_ROWS) {
                  next.splice(0, next.length - MAX_LOG_ROWS)
                }
                return next
              })
            }
          } catch {
            // Malformed
          }
        }

        socket.onclose = () => {
          if (!active) return
          setWsConnected(false)
          if (terminalRef.current) return

          if (reconnectTimerRef.current) {
            clearTimeout(reconnectTimerRef.current)
            reconnectTimerRef.current = null
          }

          if (reconnectCountRef.current < MAX_RECONNECT) {
            reconnectCountRef.current += 1
            reconnectTimerRef.current = window.setTimeout(connectWs, 3000)
          }
        }

        socket.onerror = () => {
          if (!active) return
          setWsConnected(false)
        }
      } catch {
        setWsConnected(false)
      }
    }

    connectWs()

    return () => {
      active = false
      if (reconnectTimerRef.current) {
        clearTimeout(reconnectTimerRef.current)
        reconnectTimerRef.current = null
      }
      logsAbortControllerRef.current?.abort()
      if (wsRef.current) {
        wsRef.current.close()
        wsRef.current = null
      }
    }
  }, [id])

  const planName = useMemo(() => {
    if (!run) return ''
    const p = plans.find((item) => item.id === run.plan_id)
    return p ? p.name : run.plan_id
  }, [run, plans])

  const agentName = useMemo(() => {
    if (!run) return ''
    const a = agents.find((item) => item.id === run.agent_id)
    return a ? `${a.name} (${a.hostname})` : run.agent_id
  }, [run, agents])

  const copySnapshot = async (snapshotId: string) => {
    try {
      await navigator.clipboard.writeText(snapshotId)
      setCopiedSnapshot(true)
      toastSuccess(t('common.copied'))
      setTimeout(() => setCopiedSnapshot(false), 2000)
    } catch {
      toastError(t('common.copyFailed'))
    }
  }

  if (loading) {
    return <PageLoadingState />
  }

  if (error || !run) {
    return (
      <AppErrorState
        title={t('runDetail.title')}
        message={error || t('runDetail.loadFailed')}
        onRetry={loadRun}
      />
    )
  }

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => navigate('/runs')}
            className="h-8 w-8"
            aria-label={t('common.previous')}
          >
            <ArrowLeft className="h-4 w-4" aria-hidden="true" />
          </Button>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-lg font-bold tracking-tight text-foreground font-mono">
                Run #{run.id.substring(0, 8)}
              </h2>
              <StatusBadge
                tone={statusTagType(run.status)}
                dot={run.status === 'running' || run.status === 'dispatched'}
              >
                {translateEnum('status', run.status)}
              </StatusBadge>
            </div>
            <p className="text-xs text-muted-foreground">{planName}</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {wsConnected ? (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-emerald-500/30 bg-emerald-500/10 text-[11px] text-emerald-600 dark:text-emerald-400 font-medium">
              <Radio className="h-3 w-3 animate-pulse" aria-hidden="true" />
              <span>{t('runDetail.liveConnected')}</span>
            </div>
          ) : (
            <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-border bg-muted/40 text-[11px] text-muted-foreground">
              <span className="h-2 w-2 rounded-full bg-muted-foreground/50" aria-hidden="true" />
              <span>{t('runDetail.disconnected')}</span>
            </div>
          )}
        </div>
      </div>

      {/* Info Card */}
      <Card className="border-border bg-card/60 shadow-sm">
        <CardContent className="p-4 sm:p-6 grid grid-cols-2 sm:grid-cols-4 gap-4">
          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.labels.operation')}</span>
            <div>
              <StatusBadge tone={operationTagType(run.operation)}>
                {translateEnum('runs.operations', run.operation)}
              </StatusBadge>
            </div>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.labels.agent')}</span>
            <p className="text-xs font-medium text-foreground truncate">{agentName}</p>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.labels.snapshot')}</span>
            {run.snapshot_id ? (
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={() => copySnapshot(run.snapshot_id!)}
                className="h-6 p-0 font-mono text-xs text-primary hover:underline gap-1.5 justify-start"
                aria-label={t('snapshots.copySnapshotId')}
              >
                <span className="truncate">{run.snapshot_id.substring(0, 10)}...</span>
                {copiedSnapshot ? (
                  <Check className="h-3 w-3 text-emerald-600 dark:text-emerald-400" aria-hidden="true" />
                ) : (
                  <Copy className="h-3 w-3" aria-hidden="true" />
                )}
              </Button>
            ) : (
              <p className="text-xs text-muted-foreground font-mono">—</p>
            )}
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runs.columns.duration')}</span>
            <p className="text-xs font-mono text-foreground">
              {formatDuration(run.started_at, run.finished_at)}
            </p>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.timeline.queued')}</span>
            <p className="text-xs font-mono text-muted-foreground">{formatDateTime(run.queued_at)}</p>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.timeline.started')}</span>
            <p className="text-xs font-mono text-muted-foreground">
              {run.started_at ? formatDateTime(run.started_at) : '—'}
            </p>
          </div>

          <div className="space-y-1">
            <span className="text-[11px] text-muted-foreground">{t('runDetail.timeline.finished')}</span>
            <p className="text-xs font-mono text-muted-foreground">
              {run.finished_at ? formatDateTime(run.finished_at) : '—'}
            </p>
          </div>

          {run.error_code && (
            <div className="space-y-1 col-span-2 sm:col-span-4 border-t border-border pt-3">
              <span className="text-[11px] text-destructive font-medium">{t('runDetail.labels.error')}</span>
              <div className="rounded bg-destructive/10 border border-destructive/20 p-2 text-xs font-mono text-destructive">
                <span className="font-bold">[{run.error_code}] </span>
                <span>{run.error_message || t('common.error_occurred')}</span>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Progress Card (When Available) */}
      {run.progress && (
        <Card className="border-border bg-card/60 shadow-sm">
          <CardHeader className="pb-2">
            <div className="flex items-center justify-between">
              <CardTitle className="text-xs font-semibold">
                {t('runDetail.progress.title')}
              </CardTitle>
              <span className="text-xs font-mono font-medium text-primary">
                {run.progress.percent}%
              </span>
            </div>
          </CardHeader>
          <CardContent className="space-y-3">
            <Progress value={run.progress.percent} className="h-2 bg-muted" />
            <div className="flex flex-wrap items-center justify-between text-xs text-muted-foreground gap-2 pt-1">
              <div>
                <span className="font-medium text-foreground">
                  {t('runDetail.progress.phase')}:{' '}
                </span>
                <span>{translateEnum('runDetail.phases', run.progress.phase)}</span>
              </div>
              <div>
                <span className="font-medium text-foreground">
                  {t('runDetail.progress.bytes')}:{' '}
                </span>
                <span className="font-mono">
                  {formatBytes(run.progress.bytes_done)} / {formatBytes(run.progress.bytes_total)}
                </span>
              </div>
              <div>
                <span className="font-medium text-foreground">
                  {t('runDetail.progress.files')}:{' '}
                </span>
                <span className="font-mono">
                  {run.progress.files_done} / {run.progress.files_total}
                </span>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Terminal Log Console */}
      <Card className="border-border bg-card shadow-xl overflow-hidden">
        <CardHeader className="py-3 px-4 border-b border-border bg-muted/40 flex flex-row items-center justify-between space-y-0">
          <div className="flex items-center gap-2">
            <Terminal className="h-4 w-4 text-primary" aria-hidden="true" />
            <CardTitle className="text-xs font-mono font-medium text-foreground">
              {t('runDetail.logs.title', { count: logs.length })}
            </CardTitle>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2">
              <Checkbox
                id="auto-scroll"
                checked={autoScroll}
                onCheckedChange={(checked) => setAutoScroll(checked === true)}
              />
              <label
                htmlFor="auto-scroll"
                className="text-[11px] text-muted-foreground cursor-pointer"
              >
                {t('runDetail.logs.autoScroll')}
              </label>
            </div>
            {hasMoreLogs && (
              <Button
                variant="outline"
                size="sm"
                onClick={loadMoreLogs}
                disabled={loadingLogs}
                className="h-6 text-[11px] px-2 gap-1"
              >
                {loadingLogs ? (
                  <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
                ) : (
                  <RotateCcw className="h-3 w-3" aria-hidden="true" />
                )}
                {t('runDetail.logs.loadMore')}
              </Button>
            )}
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <div
            ref={logsWrapRef}
            className="h-96 overflow-y-auto p-4 font-mono text-xs text-foreground/90 space-y-1 scrollbar-thin"
          >
            {logs.length > 0 ? (
              logs.map((log) => {
                const isError = log.level === 'error' || log.level === 'warn'
                return (
                  <div key={log.seq} className="flex gap-3 leading-relaxed hover:bg-muted/50 py-0.5 px-1 rounded">
                    <span className="text-[11px] text-muted-foreground/60 select-none w-10 shrink-0 text-right">
                      {log.seq}
                    </span>
                    <span className="text-[11px] text-muted-foreground/80 select-none shrink-0">
                      {new Date(log.timestamp).toLocaleTimeString()}
                    </span>
                    <span
                      className={`break-all ${
                        isError ? 'text-rose-600 dark:text-rose-400 font-medium' : 'text-foreground'
                      }`}
                    >
                      {log.message}
                    </span>
                  </div>
                )
              })
            ) : (
              <div className="flex h-full items-center justify-center text-xs text-muted-foreground">
                <FileText className="h-4 w-4 mr-2 opacity-50" aria-hidden="true" />
                <span>{t('runDetail.logs.empty')}</span>
              </div>
            )}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}

// web/src/views/runs/RunDetailView.vue
<template>
  <div class="detail-page">
    <div class="page-head">
      <h2 class="page-title">{{ t('runDetail.title') }}</h2>
    </div>

    <div v-if="error" class="error-state">
      <el-icon><Warning /></el-icon>
      <p>{{ error }}</p>
      <el-button type="primary" @click="loadRun" style="margin-top: 12px">{{ t('common.retry') }}</el-button>
    </div>

    <template v-else-if="run">
      <!-- Status card -->
      <el-card shadow="never" class="status-card">
        <div class="status-grid">
          <div class="status-item">
            <span class="status-label">{{ t('runDetail.labels.status') }}</span>
            <el-tag
              :type="statusTagType(run.status)"
              :effect="isRunning(run.status) ? 'dark' : 'plain'"
            >
              {{ runStatusText(run.status) }}
            </el-tag>
          </div>
          <div class="status-item">
            <span class="status-label">{{ t('runDetail.labels.operation') }}</span>
            <el-tag :type="operationTagType(run.operation)" size="default">
              {{ operationText(run.operation) }}
            </el-tag>
          </div>
          <div class="status-item">
            <span class="status-label">{{ t('runDetail.labels.plan') }}</span>
            <span>{{ planName(run.plan_id) || run.plan_id }}</span>
          </div>
          <div class="status-item">
            <span class="status-label">{{ t('runDetail.labels.agent') }}</span>
            <span>{{ agentName(run.agent_id) || run.agent_id }}</span>
          </div>
          <div class="status-item" v-if="run.snapshot_id">
            <span class="status-label">{{ t('runDetail.labels.snapshot') }}</span>
            <span class="copyable" @click="copyText(run.snapshot_id!)">
              <el-icon><CopyDocument /></el-icon>
              {{ run.snapshot_id }}
            </span>
          </div>
          <div class="status-item" v-if="run.error_code">
            <span class="status-label">{{ t('runDetail.labels.error') }}</span>
            <el-tooltip :content="run.error_message || run.error_code" placement="top">
              <el-tag type="danger" size="default" effect="plain">
                {{ run.error_code }}
              </el-tag>
            </el-tooltip>
          </div>
          <div class="status-item" v-if="run.error_message && run.error_code === null">
            <span class="status-label">{{ t('runDetail.labels.message') }}</span>
            <span>{{ run.error_message }}</span>
          </div>
        </div>

        <!-- Timeline -->
        <div class="timeline">
          <el-steps
            :active="timelineStep"
            finish-status="success"
            align-center
          >
            <el-step
              :title="t('runDetail.timeline.queued')"
              :description="formatTime(run.queued_at)"
            />
            <el-step
              :title="t('runDetail.timeline.started')"
              :description="formatTime(run.started_at || '')"
            />
            <el-step
              :title="t('runDetail.timeline.finished')"
              :description="formatTime(run.finished_at || '')"
            />
          </el-steps>
        </div>
      </el-card>

      <!-- Progress section -->
      <el-card v-if="run.progress" shadow="never" class="progress-card">
        <template #header>
          <span>{{ t('runDetail.progress.title') }}</span>
        </template>
        <div class="progress-body">
          <el-progress
            :percentage="run.progress.percent"
            :status="run.status === 'failed' ? 'exception' : undefined"
            :stroke-width="20"
            style="margin-bottom: 12px"
          />
          <div class="progress-meta">
            <span class="phase-text"><strong>{{ t('runDetail.progress.phase') }}</strong> {{ phaseText(run.progress.phase) }}</span>
            <span v-if="hasBytes(run.progress)" class="bytes-text">
              <strong>{{ t('runDetail.progress.bytes') }}</strong> {{ formatBytes(run.progress.bytes_done) }} / {{ formatBytes(run.progress.bytes_total) }}
            </span>
            <span v-if="hasFiles(run.progress)" class="files-text">
              <strong>{{ t('runDetail.progress.files') }}</strong> {{ run.progress.files_done }} / {{ run.progress.files_total }}
            </span>
            <span v-if="run.started_at && !run.finished_at" class="duration-text">
              <strong>{{ t('runDetail.progress.elapsed') }}</strong> {{ formatDuration(run.started_at, new Date().toISOString()) }}<el-icon class="is-loading" style="margin-left:4px"><Loading /></el-icon>
            </span>
          </div>
        </div>
      </el-card>

      <!-- Logs panel -->
      <el-card shadow="never" class="logs-card">
        <template #header>
          <div class="logs-header">
            <span>{{ t('runDetail.logs.title', { count: logs.length }) }}</span>
            <div class="logs-controls">
              <el-checkbox v-model="autoScroll" :label="t('runDetail.logs.autoScroll')" />
              <el-button
                type="primary"
                size="small"
                :disabled="loadingLogs || !hasMoreLogs"
                @click="loadMoreLogs"
              >
                {{ loadingLogs ? t('runDetail.logs.loading') : t('runDetail.logs.loadMore') }}
              </el-button>
              <el-tag size="small" :type="wsConnected ? 'success' : 'info'" class="ws-tag">
                <el-icon v-if="wsConnected" class="is-loading"><Loading /></el-icon>
                <el-icon v-else-if="wsClosed"><Connection /></el-icon>
                {{ wsConnected ? t('runDetail.logs.streaming') : wsClosed ? t('runDetail.logs.connected') : t('runDetail.logs.offline') }}
              </el-tag>
            </div>
          </div>
        </template>

        <div class="logs-table-wrap" ref="logsWrapEl">
          <el-table
            :data="displayLogs"
            :max-height="400"
            stripe
            size="small"
          >
            <el-table-column :label="t('runDetail.logs.seq')" width="70">
              <template #default="{ row }">{{ row.seq }}</template>
            </el-table-column>
            <el-table-column :label="t('runDetail.logs.time')" width="180">
              <template #default="{ row }">{{ formatTime(row.timestamp) }}</template>
            </el-table-column>
            <el-table-column :label="t('runDetail.logs.level')" width="80">
              <template #default="{ row }">
                <span :class="`log-level level-${row.level}`">{{ row.level }}</span>
              </template>
            </el-table-column>
            <el-table-column :label="t('runDetail.logs.message')">
              <template #default="{ row }">
                <span class="log-message">{{ row.message }}</span>
              </template>
            </el-table-column>
          </el-table>
        </div>
      </el-card>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount, watch, nextTick, computed } from 'vue'
import { useRoute } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { apiGet } from '@/api/client'
import type { Run, RunLog, RunProgress, Plan, Agent } from '@/api/types'
import { Loading, Warning, CopyDocument, Connection } from '@element-plus/icons-vue'
import { formatDateTime, translateEnum } from '@/i18n'

interface WsStateMessage {
  type: 'state'
  run: Run
}

interface WsProgressMessage {
  type: 'progress'
  progress: RunProgress
}

interface WsLogMessage {
  type: 'log'
  entry: RunLog
}

type WsMessage = WsStateMessage | WsProgressMessage | WsLogMessage

const route = useRoute()
const { t } = useI18n()
const runId = computed(() => route.params.id as string)

const STATUS_VALUE_KEYS: Record<string, string> = {
  queued: 'runs.status.queued',
  dispatched: 'runs.status.dispatched',
  running: 'runs.status.running',
  succeeded: 'runs.status.succeeded',
  failed: 'runs.status.failed',
  cancelled: 'runs.status.cancelled',
}

const OPERATION_VALUE_KEYS: Record<string, string> = {
  backup: 'runs.operations.backup',
  restore: 'runs.operations.restore',
  check: 'runs.operations.check',
  forget: 'runs.operations.forget',
}

function runStatusText(status: string): string {
  return t(STATUS_VALUE_KEYS[status] ?? 'common.status')
}

function operationText(op: string): string {
  return t(OPERATION_VALUE_KEYS[op] ?? op)
}

function phaseText(phase: string): string {
  return translateEnum('runDetail.phases', phase)
}

const run = ref<Run | null>(null)
const plans = ref<Plan[]>([])
const agents = ref<Agent[]>([])
const logs = ref<RunLog[]>([])
const loadingLogs = ref(false)
const autoScroll = ref(true)
const hasMoreLogs = ref(false)
const logsWrapEl = ref<HTMLElement | null>(null)
const error = ref('')
const wsConnected = ref(false)
const wsClosed = ref(false)

const MAX_LOG_ROWS = 5000
let ws: WebSocket | null = null
let reconnectAttempts = 0
const MAX_RECONNECT = 1

// Computed helpers
const timelineStep = computed(() => {
  if (!run.value) return 0
  if (run.value.finished_at) return 3
  if (run.value.started_at) return 2
  return 1
})

const displayLogs = computed<RunLog[]>(() => {
  // Already capped at MAX_LOG_ROWS in pushLog
  return logs.value
})

async function loadRun(): Promise<void> {
  error.value = ''
  try {
    const data = await apiGet<Run>(`/runs/${runId.value}`)
    run.value = data
    wsClosed.value = false
    wsConnected.value = false
    if (isTerminal(data.status)) {
      wsClosed.value = true
    }
  } catch (err: any) {
    error.value = err.message || t('runDetail.loadFailed')
  }
}

async function loadPlansAndAgents(): Promise<void> {
  try {
    plans.value = await apiGet<Plan[]>('/plans')
  } catch {
    // non-critical
  }
  try {
    agents.value = await apiGet<Agent[]>('/agents')
  } catch {
    // non-critical
  }
}

async function loadInitialLogs(): Promise<void> {
  loadingLogs.value = true
  try {
    const data = await apiGet<RunLog[]>(`/runs/${runId.value}/logs`, {
      limit: 500,
    })
    logs.value = data
    if (data.length > 0) {
      hasMoreLogs.value = true
    }
  } catch {
    // If logs endpoint unavailable, keep existing
  } finally {
    loadingLogs.value = false
  }
}

async function loadMoreLogs(): Promise<void> {
  if (logs.value.length === 0 || loadingLogs.value) return
  loadingLogs.value = true
  try {
    const beforeSeq = Math.min(...logs.value.map((l) => l.seq)) - 1
    if (beforeSeq <= 0) {
      hasMoreLogs.value = false
      return
    }
    const data = await apiGet<RunLog[]>(`/runs/${runId.value}/logs`, {
      before_seq: String(beforeSeq),
      limit: 500,
    })
    if (data.length < 500) {
      hasMoreLogs.value = false
    }
    // Prepend and maintain order
    const merged = [...data, ...logs.value]
    // Ensure uniqueness by seq
    const seqMap = new Map<number, RunLog>()
    for (const log of merged) {
      seqMap.set(log.seq, log)
    }
    const unique = Array.from(seqMap.values()).sort((a, b) => a.seq - b.seq)
    if (unique.length > MAX_LOG_ROWS) {
      unique.splice(0, unique.length - MAX_LOG_ROWS)
    }
    logs.value = unique
  } catch {
    // non-fatal
  } finally {
    loadingLogs.value = false
  }
}

function pushLog(entry: RunLog): void {
  // Avoid duplicates
  const idx = logs.value.findIndex((l) => l.seq === entry.seq)
  if (idx >= 0) {
    logs.value[idx] = entry
    return
  }
  logs.value.push(entry)
  if (logs.value.length > MAX_LOG_ROWS) {
    logs.value.splice(0, logs.value.length - MAX_LOG_ROWS)
  }
  if (autoScroll.value) {
    nextTick(() => {
      const el = logsWrapEl.value
      if (el) el.scrollTop = el.scrollHeight
    })
  }
}

function pushProgress(progress: RunProgress): void {
  if (run.value) {
    run.value = { ...run.value, progress }
  }
}

function pushState(r: Run): void {
  run.value = r
  if (isTerminal(r.status)) {
    wsClosed.value = true
    closeWs()
  }
}

function connectWs(): void {
  if (ws) {
    ws.close()
    ws = null
  }
  reconnectAttempts = 0
  wsConnected.value = false
  const protocol = location.protocol === 'https:' ? 'wss:' : 'ws:'
  const url = `${protocol}//${location.host}/ws/runs/${runId.value}`
  try {
    ws = new WebSocket(url)
  } catch {
    wsClosed.value = true
    return
  }

  ws.addEventListener('open', () => {
    wsConnected.value = true
    wsClosed.value = false
  })

  ws.addEventListener('message', (event: MessageEvent) => {
    try {
      const msg = JSON.parse(event.data) as WsMessage
      switch (msg.type) {
        case 'state':
          pushState(msg.run)
          break
        case 'progress':
          pushProgress(msg.progress)
          break
        case 'log':
          pushLog(msg.entry)
          break
        default:
          // Unknown type, ignore
          break
      }
    } catch {
      // Malformed message, skip
    }
  })

  ws.addEventListener('close', () => {
    wsConnected.value = false
    if (run.value && isTerminal(run.value.status)) {
      wsClosed.value = true
      return
    }
    // Reconnect once
    if (reconnectAttempts < MAX_RECONNECT) {
      reconnectAttempts++
      ws = null
      wsConnected.value = false
      setTimeout(connectWs, 3000)
    } else {
      wsClosed.value = true
    }
  })

  ws.addEventListener('error', () => {
    wsConnected.value = false
  })
}

function closeWs(): void {
  if (ws) {
    ws.close()
    ws = null
  }
  wsConnected.value = false
}

function isTerminal(status: Run['status']): boolean {
  return status === 'succeeded' || status === 'failed' || status === 'cancelled'
}

function currentRunTerminal(): boolean {
  const r = run.value
  return !r || isTerminal(r.status)
}

function isRunning(status: Run['status']): boolean {
  return status === 'running' || status === 'dispatched'
}

function hasBytes(p: RunProgress): boolean {
  return p.bytes_total > 0 || p.bytes_done > 0
}

function hasFiles(p: RunProgress): boolean {
  return p.files_total > 0 || p.files_done > 0
}

function planName(planId: string): string | undefined {
  return plans.value.find((p) => p.id === planId)?.name
}

function agentName(agentId: string): string | undefined {
  return agents.value.find((a) => a.id === agentId)?.name
}

function formatTime(iso: string | null | undefined): string {
  if (!iso) return '—'
  return formatDateTime(iso, { second: '2-digit' })
}

function formatBytes(bytes: number): string {
  if (bytes <= 0) return '0 B'
  const units = ['B', 'KB', 'MB', 'GB', 'TB']
  const i = Math.floor(Math.log(bytes) / Math.log(1024))
  const idx = Math.min(i, units.length - 1)
  return (bytes / Math.pow(1024, idx)).toFixed(1) + ' ' + units[idx]
}

function formatDuration(started: string, finished: string): string {
  const start = new Date(started).getTime()
  const finish = new Date(finished).getTime()
  if (isNaN(start) || isNaN(finish)) return '—'
  const diff = Math.max(0, finish - start)
  const totalSec = Math.floor(diff / 1000)
  const h = Math.floor(totalSec / 3600)
  const m = Math.floor((totalSec % 3600) / 60)
  const s = totalSec % 60
  if (totalSec < 60) return `${s}${t('time.secShort')}`
  if (h > 0) return `${h}${t('time.hourShort')} ${m}${t('time.minShort')} ${s}${t('time.secShort')}`
  if (m > 0) return `${m}${t('time.minShort')} ${s}${t('time.secShort')}`
  return `${s}${t('time.secShort')}`
}

function statusTagType(status: Run['status']): 'success' | 'danger' | 'primary' | 'warning' | 'info' {
  switch (status) {
    case 'succeeded':
      return 'success'
    case 'failed':
      return 'danger'
    case 'running':
    case 'dispatched':
      return 'primary'
    case 'cancelled':
      return 'warning'
    default:
      return 'info'
  }
}

function operationTagType(op: Run['operation']): 'success' | 'danger' | 'primary' | 'warning' | 'info' {
  switch (op) {
    case 'backup':
      return 'success'
    case 'restore':
      return 'primary'
    case 'check':
      return 'info'
    case 'forget':
      return 'warning'
    default:
      return 'info'
  }
}

async function copyText(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text)
  } catch {
    // fail silently
  }
}

// Watch for runId change (route change)
watch(
  runId,
  async (newId) => {
    if (!newId) return
    closeWs()
    logs.value = []
    run.value = null
    error.value = ''
    await loadRun()
    await loadInitialLogs()
    if (!error.value && !currentRunTerminal()) {
      connectWs()
    }
  },
)

onMounted(async () => {
  await loadPlansAndAgents()
  await loadRun()
  if (!error.value) {
    await loadInitialLogs()
    if (run.value && !isTerminal(run.value.status)) {
      connectWs()
    }
  }
})

onBeforeUnmount(() => {
  closeWs()
})
</script>

<style scoped>
.detail-page {
  max-width: 1400px;
  margin: 0 auto;
}
.page-head {
  margin-bottom: 16px;
}
.page-title {
  margin: 0;
  font-size: 22px;
  font-weight: 600;
}
.status-card {
  margin-bottom: 16px;
}
.status-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
  gap: 12px;
  margin-bottom: 20px;
}
.status-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.status-label {
  font-size: 12px;
  color: #909399;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.timeline {
  padding-top: 16px;
  border-top: 1px solid #ebeef5;
}
.progress-card {
  margin-bottom: 16px;
}
.progress-body {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.progress-meta {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  font-size: 13px;
  color: #303133;
}
.phase-text,
.bytes-text,
.files-text,
.duration-text {
  white-space: nowrap;
}
.copyable {
  cursor: pointer;
  font-family: 'Courier New', Courier, monospace;
  font-size: 13px;
  color: #409eff;
  user-select: none;
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.copyable:hover {
  color: #2b7fd5;
}
.logs-card {
  margin-bottom: 16px;
}
.logs-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.logs-controls {
  display: flex;
  align-items: center;
  gap: 12px;
}
.ws-tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.log-table-wrap {
  font-family: 'Courier New', Courier, monospace;
}
.log-message {
  white-space: pre-wrap;
  word-break: break-all;
}
.log-level {
  font-weight: 600;
  font-size: 11px;
  text-transform: uppercase;
}
.level-error {
  color: #f56c6c;
}
.level-warn,
.level-warning {
  color: #e6a23c;
}
.level-info {
  color: #409eff;
}
.level-debug,
.level-trace {
  color: #909399;
}
.level-fatal {
  color: #f56c6c;
}
.error-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px;
  color: #f56c6c;
}
</style>
