// web/src/views/runs/RunsView.tsx
import React, { useEffect, useState, useMemo, useRef } from 'react'
import { Link } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Card, CardContent } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { apiGet, apiPost, isApiClientError, isAbortError } from '@/api/client'
import { formatDateTime, translateEnum } from '@/i18n'
import type { Run, Agent, Plan } from '@/api/types'
import { AppEmptyState } from '@/components/AppEmptyState'
import { AppErrorState } from '@/components/AppErrorState'
import { StatusBadge } from '@/components/StatusBadge'
import { ConfirmActionDialog } from '@/components/ConfirmActionDialog'
import { PageLoadingState } from '@/components/PageLoadingState'
import { toastSuccess, toastError } from '@/lib/toast'
import {
  STATUS_VALUE_KEYS,
  OPERATION_VALUE_KEYS,
  statusTagType,
  operationTagType,
  formatDuration,
} from '@/utils/runDisplay'
import { RefreshCw, Search, XSquare, ChevronLeft, ChevronRight, RotateCcw } from 'lucide-react'

export interface RunFilters {
  planId: string
  agentId: string
  status: string
  operation: string
}

export interface RunQuery {
  filters: RunFilters
  limit: number
  offset: number
}

const DEFAULT_FILTERS: RunFilters = {
  planId: '',
  agentId: 'all',
  status: 'all',
  operation: 'all',
}

export const RunsView: React.FC = () => {
  const { t } = useTranslation()

  const [runs, setRuns] = useState<Run[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [plans, setPlans] = useState<Plan[]>([])

  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  // Filters state
  const [filters, setFilters] = useState<RunFilters>(DEFAULT_FILTERS)
  const [planIdInput, setPlanIdInput] = useState('')

  // Pagination state
  const [limit, setLimit] = useState(20)
  const [offset, setOffset] = useState(0)

  // Cancel run dialog
  const [cancelDialogOpen, setCancelDialogOpen] = useState(false)
  const [runToCancel, setRunToCancel] = useState<Run | null>(null)

  const abortControllerRef = useRef<AbortController | null>(null)
  const currentQueryRef = useRef<RunQuery>({
    filters: DEFAULT_FILTERS,
    limit: 20,
    offset: 0,
  })
  const didMountRef = useRef(false)

  const statusOptions = useMemo(
    () =>
      Object.entries(STATUS_VALUE_KEYS).map(([value, key]) => ({
        value,
        label: t(key),
      })),
    [t]
  )

  const operationOptions = useMemo(
    () =>
      Object.entries(OPERATION_VALUE_KEYS).map(([value, key]) => ({
        value,
        label: t(key),
      })),
    [t]
  )

  const planMap = useMemo(() => {
    const map = new Map<string, Plan>()
    for (const p of plans) {
      map.set(p.id, p)
    }
    return map
  }, [plans])

  const loadRuns = async (query: RunQuery) => {
    abortControllerRef.current?.abort()
    const controller = new AbortController()
    abortControllerRef.current = controller
    currentQueryRef.current = query

    setLoading(true)
    setError(null)
    try {
      const params: Record<string, string | number | undefined> = {
        limit: query.limit,
        offset: query.offset,
        plan_id: query.filters.planId.trim() || undefined,
        agent_id: query.filters.agentId === 'all' ? undefined : query.filters.agentId,
        status: query.filters.status === 'all' ? undefined : query.filters.status,
        operation: query.filters.operation === 'all' ? undefined : query.filters.operation,
      }
      const data = await apiGet<Run[]>('/runs', params, { signal: controller.signal })
      setRuns(data)
      setOffset(query.offset)
      setLimit(query.limit)
    } catch (err: unknown) {
      if (isAbortError(err)) return
      setError(isApiClientError(err) ? err.message : t('runs.loadFailed'))
    } finally {
      if (abortControllerRef.current === controller) {
        setLoading(false)
      }
    }
  }

  const loadMeta = async () => {
    try {
      const [agentList, planList] = await Promise.all([
        apiGet<Agent[]>('/agents'),
        apiGet<Plan[]>('/plans'),
      ])
      setAgents(agentList)
      setPlans(planList)
    } catch {
      // Non-blocking
    }
  }

  useEffect(() => {
    loadMeta()
    loadRuns({
      filters: DEFAULT_FILTERS,
      limit: 20,
      offset: 0,
    })
    return () => {
      abortControllerRef.current?.abort()
    }
  }, [])

  // 400ms debounce on planIdInput (skipping first render)
  useEffect(() => {
    if (!didMountRef.current) {
      didMountRef.current = true
      return
    }
    const timer = setTimeout(() => {
      const nextFilters: RunFilters = { ...filters, planId: planIdInput }
      setFilters(nextFilters)
      loadRuns({ filters: nextFilters, limit, offset: 0 })
    }, 400)
    return () => clearTimeout(timer)
  }, [planIdInput])

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault()
    const nextFilters: RunFilters = { ...filters, planId: planIdInput }
    setFilters(nextFilters)
    loadRuns({ filters: nextFilters, limit, offset: 0 })
  }

  const handleReset = () => {
    setPlanIdInput('')
    setFilters(DEFAULT_FILTERS)
    loadRuns({ filters: DEFAULT_FILTERS, limit, offset: 0 })
  }

  const handleAgentChange = (val: string) => {
    const nextFilters: RunFilters = { ...filters, agentId: val }
    setFilters(nextFilters)
    loadRuns({ filters: nextFilters, limit, offset: 0 })
  }

  const handleStatusChange = (val: string) => {
    const nextFilters: RunFilters = { ...filters, status: val }
    setFilters(nextFilters)
    loadRuns({ filters: nextFilters, limit, offset: 0 })
  }

  const handleOpChange = (val: string) => {
    const nextFilters: RunFilters = { ...filters, operation: val }
    setFilters(nextFilters)
    loadRuns({ filters: nextFilters, limit, offset: 0 })
  }

  const handleLimitChange = (val: string) => {
    const newLimit = Number(val)
    setLimit(newLimit)
    loadRuns({ filters, limit: newLimit, offset: 0 })
  }

  const handlePageChange = (newOffset: number) => {
    loadRuns({ filters, limit, offset: newOffset })
  }

  const isCancelable = (status: string) => {
    return status === 'queued' || status === 'dispatched' || status === 'running'
  }

  const openCancelDialog = (e: React.MouseEvent, run: Run) => {
    e.stopPropagation()
    setRunToCancel(run)
    setCancelDialogOpen(true)
  }

  const handleCancelConfirm = async () => {
    if (!runToCancel) return
    try {
      await apiPost(`/runs/${runToCancel.id}/cancel`, {})
      toastSuccess(t('runs.cancelled'))
      await loadRuns(currentQueryRef.current)
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('runs.cancelFailed'))
    }
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            {t('runs.title')}
          </h2>
          <p className="text-xs text-muted-foreground">
            {t('runs.subtitle')}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => loadRuns(currentQueryRef.current)}
          disabled={loading}
          className="h-8 text-xs gap-1.5 self-start sm:self-auto"
        >
          <RefreshCw className="h-3.5 w-3.5" aria-hidden="true" />
          {t('common.refresh')}
        </Button>
      </div>

      {/* Filter Card */}
      <Card className="border-border bg-card/40 shadow-sm">
        <CardContent className="p-4">
          <form onSubmit={handleSearch} className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-3">
            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">{t('runs.filters.plan')}</Label>
              <Input
                placeholder={t('runs.filters.planIdPlaceholder')}
                value={planIdInput}
                onChange={(e) => setPlanIdInput(e.target.value)}
                className="h-8 text-xs font-mono"
              />
            </div>

            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">{t('runs.filters.agent')}</Label>
              <Select value={filters.agentId} onValueChange={handleAgentChange}>
                <SelectTrigger className="h-8 text-xs">
                  <SelectValue placeholder={t('runs.filters.agent')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" className="text-xs">
                    {t('common.allAgents')}
                  </SelectItem>
                  {agents.map((a) => (
                    <SelectItem key={a.id} value={a.id} className="text-xs">
                      {a.name} ({a.hostname})
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">{t('runs.filters.status')}</Label>
              <Select value={filters.status} onValueChange={handleStatusChange}>
                <SelectTrigger className="h-8 text-xs">
                  <SelectValue placeholder={t('runs.filters.status')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" className="text-xs">
                    {t('common.all')}
                  </SelectItem>
                  {statusOptions.map((s) => (
                    <SelectItem key={s.value} value={s.value} className="text-xs">
                      {s.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-1">
              <Label className="text-[11px] text-muted-foreground">{t('runs.filters.operation')}</Label>
              <Select value={filters.operation} onValueChange={handleOpChange}>
                <SelectTrigger className="h-8 text-xs">
                  <SelectValue placeholder={t('runs.filters.operation')} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" className="text-xs">
                    {t('common.all')}
                  </SelectItem>
                  {operationOptions.map((o) => (
                    <SelectItem key={o.value} value={o.value} className="text-xs">
                      {o.label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="flex items-end gap-2 col-span-1 sm:col-span-2 md:col-span-4 lg:col-span-1">
              <Button type="submit" size="sm" className="h-8 text-xs flex-1 gap-1">
                <Search className="h-3 w-3" aria-hidden="true" />
                {t('common.search')}
              </Button>
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={handleReset}
                className="h-8 text-xs gap-1"
              >
                <RotateCcw className="h-3 w-3" aria-hidden="true" />
                {t('common.reset')}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>

      {error ? (
        <AppErrorState title={t('runs.title')} message={error} onRetry={() => loadRuns(currentQueryRef.current)} />
      ) : (
        <Card className="border-border bg-card/60 shadow-sm">
          <CardContent className="p-0">
            {loading && runs.length === 0 ? (
              <PageLoadingState compact />
            ) : runs.length > 0 ? (
              <div className="rounded-md overflow-hidden">
                {/* Desktop table */}
                <div className="hidden md:block overflow-x-auto">
                  <Table className="min-w-[850px]">
                    <TableHeader>
                      <TableRow className="border-border hover:bg-transparent">
                        <TableHead className="text-xs font-medium">{t('runs.columns.queuedAt')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('dashboard.plan')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('runs.filters.operation')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('common.status')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('runs.columns.snapshot')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('runs.columns.duration')}</TableHead>
                        <TableHead className="text-xs font-medium text-right">{t('common.actions')}</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {runs.map((run) => {
                        const plan = planMap.get(run.plan_id)
                        const planLabel = plan ? plan.name : run.plan_id
                        const canCancel = isCancelable(run.status)
                        return (
                          <TableRow key={run.id} className="border-border hover:bg-muted/40">
                            <TableCell className="text-xs text-muted-foreground font-mono">
                              <Link
                                to={`/runs/${run.id}`}
                                className="hover:text-primary hover:underline"
                              >
                                {formatDateTime(run.queued_at)}
                              </Link>
                            </TableCell>
                            <TableCell className="font-medium text-xs text-foreground">
                              <Link
                                to={`/runs/${run.id}`}
                                className="hover:text-primary hover:underline"
                              >
                                {planLabel}
                              </Link>
                            </TableCell>
                            <TableCell className="text-xs">
                              <StatusBadge tone={operationTagType(run.operation)}>
                                {translateEnum('runs.operations', run.operation)}
                              </StatusBadge>
                            </TableCell>
                            <TableCell className="text-xs">
                              <StatusBadge
                                tone={statusTagType(run.status)}
                                dot={run.status === 'running' || run.status === 'dispatched'}
                              >
                                {translateEnum('status', run.status)}
                              </StatusBadge>
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground font-mono">
                              {run.snapshot_id ? (
                                <Tooltip>
                                  <TooltipTrigger asChild>
                                    <span className="truncate block max-w-[100px] underline decoration-dotted">
                                      {run.snapshot_id.substring(0, 8)}...
                                    </span>
                                  </TooltipTrigger>
                                  <TooltipContent className="text-[11px] font-mono">
                                    {run.snapshot_id}
                                  </TooltipContent>
                                </Tooltip>
                              ) : (
                                '—'
                              )}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground font-mono">
                              {formatDuration(run.started_at, run.finished_at)}
                            </TableCell>
                            <TableCell className="text-xs text-right">
                              {canCancel && (
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  onClick={(e) => openCancelDialog(e, run)}
                                  className="h-7 text-xs text-rose-600 dark:text-rose-400 hover:text-rose-700 dark:hover:text-rose-300 gap-1"
                                  aria-label={t('runs.cancel')}
                                >
                                  <XSquare className="h-3.5 w-3.5" aria-hidden="true" />
                                  {t('common.cancel')}
                                </Button>
                              )}
                            </TableCell>
                          </TableRow>
                        )
                      })}
                    </TableBody>
                  </Table>
                </div>

                {/* Mobile Cards */}
                <div className="md:hidden divide-y divide-border">
                  {runs.map((run) => {
                    const plan = planMap.get(run.plan_id)
                    const planLabel = plan ? plan.name : run.plan_id
                    const canCancel = isCancelable(run.status)
                    return (
                      <div key={run.id} className="p-3 space-y-2 text-xs">
                        <div className="flex items-center justify-between gap-2">
                          <Link
                            to={`/runs/${run.id}`}
                            className="font-semibold text-foreground hover:text-primary hover:underline"
                          >
                            {planLabel}
                          </Link>
                          <StatusBadge
                            tone={statusTagType(run.status)}
                            dot={run.status === 'running' || run.status === 'dispatched'}
                          >
                            {translateEnum('status', run.status)}
                          </StatusBadge>
                        </div>
                        <div className="grid grid-cols-2 gap-1 text-[11px] text-muted-foreground font-mono">
                          <div>
                            <span className="text-muted-foreground/70">{t('runs.columns.queuedAt')}: </span>
                            {formatDateTime(run.queued_at)}
                          </div>
                          <div>
                            <span className="text-muted-foreground/70">{t('runs.columns.duration')}: </span>
                            {formatDuration(run.started_at, run.finished_at)}
                          </div>
                        </div>
                        <div className="flex items-center justify-between pt-1">
                          <StatusBadge tone={operationTagType(run.operation)}>
                            {translateEnum('runs.operations', run.operation)}
                          </StatusBadge>
                          <div className="flex items-center gap-2">
                            {canCancel && (
                              <Button
                                variant="ghost"
                                size="sm"
                                onClick={(e) => openCancelDialog(e, run)}
                                className="h-7 text-xs text-rose-600 dark:text-rose-400 hover:text-rose-700 dark:hover:text-rose-300 gap-1"
                                aria-label={t('runs.cancel')}
                              >
                                <XSquare className="h-3.5 w-3.5" aria-hidden="true" />
                                {t('common.cancel')}
                              </Button>
                            )}
                            <Button
                              asChild
                              variant="outline"
                              size="sm"
                              className="h-7 text-xs"
                            >
                              <Link to={`/runs/${run.id}`}>
                                {t('common.actions')}
                              </Link>
                            </Button>
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>

                {/* Pagination footer */}
                <div className="flex items-center justify-between p-3 border-t border-border bg-card/40">
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-muted-foreground">{t('runs.rowsPerPage')}</span>
                    <Select value={String(limit)} onValueChange={handleLimitChange}>
                      <SelectTrigger className="h-7 w-16 text-xs">
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        <SelectItem value="10" className="text-xs">10</SelectItem>
                        <SelectItem value="20" className="text-xs">20</SelectItem>
                        <SelectItem value="50" className="text-xs">50</SelectItem>
                      </SelectContent>
                    </Select>
                  </div>

                  <div className="flex items-center gap-2">
                    <span className="text-xs text-muted-foreground">
                      {t('runs.offset')} {offset} – {offset + runs.length}
                    </span>
                    <Button
                      variant="outline"
                      size="icon"
                      disabled={offset === 0 || loading}
                      onClick={() => handlePageChange(Math.max(0, offset - limit))}
                      className="h-7 w-7"
                      aria-label={t('common.previous')}
                    >
                      <ChevronLeft className="h-3.5 w-3.5" aria-hidden="true" />
                    </Button>
                    <Button
                      variant="outline"
                      size="icon"
                      disabled={runs.length < limit || loading}
                      onClick={() => handlePageChange(offset + limit)}
                      className="h-7 w-7"
                      aria-label={t('common.next')}
                    >
                      <ChevronRight className="h-3.5 w-3.5" aria-hidden="true" />
                    </Button>
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-8">
                <AppEmptyState
                  title={t('runs.emptyRuns')}
                  description={t('runs.emptyRuns_desc')}
                />
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Cancel Confirmation Dialog */}
      <ConfirmActionDialog
        open={cancelDialogOpen}
        onOpenChange={setCancelDialogOpen}
        title={t('runs.cancelConfirmTitle')}
        description={t('runs.cancelConfirmDesc')}
        confirmText={t('runs.cancel')}
        destructive
        onConfirm={handleCancelConfirm}
      />
    </div>
  )
}

// web/src/views/runs/RunsView.vue
<template>
  <div>
    <div class="page-head">
      <h2 class="page-title">{{ t('runs.title') }}</h2>
    </div>

    <el-card class="filter-card" shadow="never">
      <el-form :model="filters" inline>
        <el-form-item :label="t('runs.filters.plan')">
          <el-input
            v-model="filters.plan_id"
            :placeholder="t('runs.filters.planIdPlaceholder')"
            clearable
            style="width: 220px"
            @input="debounceReset"
          />
        </el-form-item>
        <el-form-item :label="t('runs.filters.agent')">
          <el-select
            v-model="filters.agent_id"
            :placeholder="t('runs.filters.agent')"
            clearable
            filterable
            style="width: 220px"
            @change="onFilterChange"
          >
            <el-option
              v-for="a in agents"
              :key="a.id"
              :label="`${a.name} (${a.hostname})`"
              :value="a.id"
            />
          </el-select>
        </el-form-item>
        <el-form-item :label="t('runs.filters.status')">
          <el-select
            v-model="filters.status"
            :placeholder="t('runs.filters.status')"
            clearable
            style="width: 160px"
            @change="onFilterChange"
          >
            <el-option
              v-for="s in statusOptions"
              :key="s.value"
              :label="s.label"
              :value="s.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item :label="t('runs.filters.operation')">
          <el-select
            v-model="filters.operation"
            :placeholder="t('runs.filters.operation')"
            clearable
            style="width: 160px"
            @change="onFilterChange"
          >
            <el-option
              v-for="o in operationOptions"
              :key="o.value"
              :label="o.label"
              :value="o.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item>
          <el-button type="primary" @click="loadRuns">{{ t('common.search') }}</el-button>
          <el-button @click="resetFilters">{{ t('common.reset') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>

    <div v-if="error" class="error-state">
      <el-icon><Warning /></el-icon>
      <p>{{ error }}</p>
      <el-button type="primary" @click="loadRuns" style="margin-top: 12px">{{ t('common.retry') }}</el-button>
    </div>

    <div v-else-if="loading" style="text-align: center; padding: 40px">
      <el-icon class="is-loading"><Loading /></el-icon>
    </div>

    <el-table
      v-else
      :data="runs"
      stripe
      row-key="id"
      style="width: 100%"
      @row-click="onRowClick"
    >
      <el-table-column :label="t('runs.columns.queuedAt')" width="200" sortable>
        <template #default="{ row }">
          {{ formatTime(row.queued_at) }}
        </template>
      </el-table-column>
      <el-table-column :label="t('dashboard.plan')" width="180">
        <template #default="{ row }">
          {{ planName(row.plan_id) || row.plan_id }}
        </template>
      </el-table-column>
      <el-table-column :label="t('runs.filters.operation')" width="100">
        <template #default="{ row }">
          <el-tag :type="operationTagType(row.operation)" size="small">
            {{ operationText(row.operation) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column :label="t('common.status')" width="120">
        <template #default="{ row }">
          <el-tag
            :type="statusTagType(row.status)"
            size="small"
            :effect="isRunning(row.status) ? 'dark' : 'plain'"
          >
            {{ statusText(row.status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column :label="t('runs.columns.snapshot')" width="120">
        <template #default="{ row }">
          <template v-if="row.snapshot_id">
            <el-tooltip :content="row.snapshot_id" placement="top">
              <span
                class="copyable"
                @click.stop="copyText(row.snapshot_id!)"
              >
                <el-icon><CopyDocument /></el-icon>
                {{ shortCode(row.snapshot_id!) }}
              </span>
            </el-tooltip>
          </template>
          <span v-else class="dim-text">—</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('runs.columns.duration')" width="110">
        <template #default="{ row }">
          <template v-if="row.started_at && row.finished_at">
            {{ formatDuration(row.started_at, row.finished_at) }}
          </template>
          <template v-else-if="row.started_at && !row.finished_at">
            <span class="dim-text">{{ formatDuration(row.started_at, new Date().toISOString()) }}<el-icon class="is-loading" style="margin-left:4px"><Loading /></el-icon></span>
          </template>
          <span v-else class="dim-text">—</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('runs.columns.error')" width="140">
        <template #default="{ row }">
          <el-tooltip
            v-if="row.error_code"
            :content="row.error_message || row.error_code"
            placement="top"
          >
            <el-tag type="danger" size="small" effect="plain">
              {{ row.error_code }}
            </el-tag>
          </el-tooltip>
          <span v-else class="dim-text">—</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('common.actions')" width="80" fixed="right">
        <template #default="{ row }">
          <el-button
            v-if="row.status === 'running'"
            size="small"
            type="danger"
            link
            @click.stop="cancelRun(row.id)"
          >
            {{ t('runs.cancel') }}
          </el-button>
          <span v-else>&nbsp;</span>
        </template>
      </el-table-column>
    </el-table>

    <el-pagination
      v-if="!loading && !error"
      :current-page="page"
      :page-size="limit"
      :page-sizes="[10, 20, 50]"
      layout="prev, pager, next, sizes"
      style="margin-top: 16px; justify-content: flex-end"
      @current-change="onPageChange"
      @size-change="onSizeChange"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { apiGet, apiPost } from '@/api/client'
import type { Run, Plan, Agent, RunQueryParams } from '@/api/types'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Loading, Warning, CopyDocument } from '@element-plus/icons-vue'
import { formatDateTime } from '@/i18n'

const router = useRouter()
const { t } = useI18n()

// API values map to translation keys; query params stay untouched.
const STATUS_VALUE_KEYS: Record<string, string> = {
  queued: 'runs.status.queued',
  dispatched: 'runs.status.dispatched',
  running: 'runs.status.running',
  succeeded: 'runs.status.succeeded',
  failed: 'runs.status.failed',
  cancelled: 'runs.status.cancelled',
}

const OPERATION_VALUE_KEYS: Record<string, string> = {
  backup: 'runs.operations.backup',
  restore: 'runs.operations.restore',
  check: 'runs.operations.check',
  forget: 'runs.operations.forget',
}

function statusText(status: string): string {
  return t(STATUS_VALUE_KEYS[status] ?? 'common.status')
}

function operationText(op: string): string {
  return t(OPERATION_VALUE_KEYS[op] ?? op)
}

const runs = ref<Run[]>([])
const plans = ref<Plan[]>([])
const agents = ref<Agent[]>([])
const loading = ref(false)
const error = ref('')
const page = ref(1)
const limit = ref(20)

const filters = ref<RunQueryParams>({
  plan_id: '',
  agent_id: '',
  status: '',
  operation: '',
  limit: undefined,
  offset: undefined,
})

const statusOptions = computed(() =>
  Object.entries(STATUS_VALUE_KEYS).map(([value, key]) => ({ value, label: t(key) })),
)

const operationOptions = computed(() =>
  Object.entries(OPERATION_VALUE_KEYS).map(([value, key]) => ({ value, label: t(key) })),
)

let debounceTimer: ReturnType<typeof setTimeout> | null = null

function debounceReset(): void {
  if (debounceTimer) clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => {
    page.value = 1
    loadRuns()
  }, 400)
}

function onFilterChange(): void {
  page.value = 1
  loadRuns()
}

function resetFilters(): void {
  filters.value = {
    plan_id: '',
    agent_id: '',
    status: '',
    operation: '',
    limit: undefined,
    offset: undefined,
  }
  page.value = 1
  loadRuns()
}

async function loadRuns(): Promise<void> {
  loading.value = true
  error.value = ''
  try {
    const params: Record<string, string | number | undefined> = {
      ...filters.value,
      limit: limit.value,
      offset: (page.value - 1) * limit.value,
    }
    // Strip empty strings so server ignores them
    Object.keys(params).forEach((k) => {
      if (params[k] === '') {
        delete params[k]
      }
    })
    runs.value = await apiGet<Run[]>('/runs', params)
  } catch (err: any) {
    error.value = err.message || t('runs.loadFailed')
    runs.value = []
  } finally {
    loading.value = false
  }
}

async function loadPlansAndAgents(): Promise<void> {
  try {
    plans.value = await apiGet<Plan[]>('/plans')
  } catch {
    // non-critical
  }
  try {
    agents.value = await apiGet<Agent[]>('/agents')
  } catch {
    // non-critical
  }
}

function planName(planId: string): string | undefined {
  return plans.value.find((p) => p.id === planId)?.name
}

function onPageChange(p: number): void {
  page.value = p
  loadRuns()
}

function onSizeChange(size: number): void {
  limit.value = size
  page.value = 1
  loadRuns()
}

function statusTagType(status: Run['status']): 'success' | 'danger' | 'primary' | 'warning' | 'info' {
  switch (status) {
    case 'succeeded':
      return 'success'
    case 'failed':
      return 'danger'
    case 'running':
    case 'dispatched':
      return 'primary'
    case 'cancelled':
      return 'warning'
    case 'queued':
    default:
      return 'info'
  }
}

function operationTagType(op: Run['operation']): 'success' | 'danger' | 'primary' | 'warning' | 'info' {
  switch (op) {
    case 'backup':
      return 'success'
    case 'restore':
      return 'primary'
    case 'check':
      return 'info'
    case 'forget':
      return 'warning'
    default:
      return 'info'
  }
}

function isRunning(status: Run['status']): boolean {
  return status === 'running' || status === 'dispatched'
}

function shortCode(snapshotId: string): string {
  return snapshotId.length > 12 ? snapshotId.slice(-8) : snapshotId
}

function formatTime(iso: string | null): string {
  if (!iso) return '—'
  return formatDateTime(iso, { second: '2-digit' })
}

function formatDuration(started: string, finished: string): string {
  const start = new Date(started).getTime()
  const finish = new Date(finished).getTime()
  if (isNaN(start) || isNaN(finish)) return '—'
  const diff = Math.max(0, finish - start)
  const totalSec = Math.floor(diff / 1000)
  const h = Math.floor(totalSec / 3600)
  const m = Math.floor((totalSec % 3600) / 60)
  const s = totalSec % 60
  if (totalSec < 60) return `${s}${t('time.secShort')}`
  if (h > 0) return `${h}${t('time.hourShort')} ${m}${t('time.minShort')} ${s}${t('time.secShort')}`
  if (m > 0) return `${m}${t('time.minShort')} ${s}${t('time.secShort')}`
  return `${s}${t('time.secShort')}`
}

async function cancelRun(runId: string): Promise<void> {
  try {
    await ElMessageBox.confirm(t('runs.cancelDialog.confirm'), t('runs.cancelDialog.title'), {
      type: 'warning',
      confirmButtonText: t('runs.cancelDialog.confirmButton'),
      cancelButtonText: t('runs.cancelDialog.keepRunning'),
    })
    await apiPost(`/runs/${runId}/cancel`)
    ElMessage.success(t('runs.cancellationRequested'))
    await loadRuns()
  } catch (err: any) {
    if (err === 'cancel' || err === 'closed') return
    ElMessage.error(err.message || t('runs.cancelFailed'))
  }
}

function onRowClick(row: Run): void {
  router.push(`/runs/${row.id}`)
}

async function copyText(text: string): Promise<void> {
  try {
    await navigator.clipboard.writeText(text)
    ElMessage.success(t('common.copied'))
  } catch {
    ElMessage.error(t('common.copyFailed'))
  }
}

onMounted(async () => {
  await loadPlansAndAgents()
  await loadRuns()
})

onBeforeUnmount(() => {
  if (debounceTimer) clearTimeout(debounceTimer)
})
</script>

<style scoped>
.page-head {
  margin-bottom: 16px;
}
.page-title {
  margin: 0;
  font-size: 22px;
  font-weight: 600;
}
.filter-card {
  margin-bottom: 16px;
}
.error-state {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 40px;
  color: #f56c6c;
}
.copyable {
  cursor: pointer;
  font-family: 'Courier New', Courier, monospace;
  font-size: 12px;
  color: #409eff;
  user-select: none;
  display: inline-flex;
  align-items: center;
  gap: 4px;
}
.copyable:hover {
  color: #2b7fd5;
}
.dim-text {
  color: #909399;
}
.el-pagination {
  display: flex;
}
</style>
