// web/src/views/plans/PlanForm.vue
<template>
  <el-form ref="formRef" :model="props.model" :rules="rules" label-position="top" size="default">
    <el-row :gutter="16">
      <el-col :span="12">
        <el-form-item :label="t('plans.form.name')" prop="name">
          <el-input v-model="props.model.name" :placeholder="t('plans.form.namePlaceholder')" />
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.kind')" prop="kind">
          <el-select v-model="props.model.kind" :placeholder="t('plans.form.kindPlaceholder')" @change="onKindChange">
            <el-option v-for="k in planKinds" :key="k.value" :label="k.label" :value="k.value" />
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.agent')" prop="agent_id">
          <el-select v-model="props.model.agent_id" filterable :placeholder="t('plans.form.agent')" @change="onAgentChange">
            <el-option v-for="a in props.agents" :key="a.id" :label="`${a.name} (${statusText(a.status)})`" :value="a.id">
              <span>{{ a.name }}</span>
              <el-tag
                :type="a.status === 'online' ? 'success' : 'info'"
                size="small"
                style="margin-left: 8px"
              >
                {{ statusText(a.status) }}
              </el-tag>
            </el-option>
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.repository')" prop="repository_id">
          <el-select v-model="props.model.repository_id" :placeholder="t('plans.form.repository')" filterable>
            <el-option v-for="r in filteredRepos" :key="r.id" :label="`${r.storage_target_name} @ ${r.agent_name}`" :value="r.id">
              <span>{{ r.storage_target_name }} @ {{ r.agent_name }}</span>
              <span style="color: #999; margin-left: 8px; font-size: 12px">{{ r.repository_path }}</span>
            </el-option>
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.schedule')" prop="schedule">
          <el-input v-model="props.model.schedule" :placeholder="t('plans.form.schedulePlaceholder')" />
          <div class="presets">
            <span class="preset-label">{{ t('plans.form.presets') }}</span>
            <el-tag
              v-for="p in cronPresets"
              :key="p.value"
              size="small"
              class="preset-tag"
              @click="props.model.schedule = p.value"
            >
              {{ p.label }}
            </el-tag>
          </div>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.timezone')" prop="timezone">
          <el-select v-model="props.model.timezone" filterable :placeholder="t('plans.form.timezonePlaceholder')" clearable>
            <el-option v-for="tz in IANA_TIMEZONES" :key="tz" :label="tz" :value="tz" />
          </el-select>
        </el-form-item>
      </el-col>
      <el-col :span="12">
        <el-form-item :label="t('plans.form.timeoutSeconds')" prop="timeout_seconds">
          <el-input-number
            :model-value="props.model.timeout_seconds"
            :min="1"
            :step="60"
            :controls-position="'right'"
            @update:model-value="v => props.model.timeout_seconds = v ?? 3600"
          />
        </el-form-item>
      </el-col>
      <el-col :span="24">
        <el-form-item :label="t('plans.form.retention')" prop="retention">
          <el-row :gutter="8">
            <el-col :span="6">
              <el-input-number
                :model-value="props.model.retention.keep_last"
                :min="0"
                :step="1"
                :controls-position="'right'"
                placeholder="keep_last"
                @update:model-value="v => props.model.retention.keep_last = v ?? 0"
              />
            </el-col>
            <el-col :span="6">
              <el-input-number
                :model-value="props.model.retention.keep_daily"
                :min="0"
                :step="1"
                :controls-position="'right'"
                placeholder="keep_daily"
                @update:model-value="v => props.model.retention.keep_daily = v ?? 0"
              />
            </el-col>
            <el-col :span="6">
              <el-input-number
                :model-value="props.model.retention.keep_weekly"
                :min="0"
                :step="1"
                :controls-position="'right'"
                placeholder="keep_weekly"
                @update:model-value="v => props.model.retention.keep_weekly = v ?? 0"
              />
            </el-col>
            <el-col :span="6">
              <el-input-number
                :model-value="props.model.retention.keep_monthly"
                :min="0"
                :step="1"
                :controls-position="'right'"
                placeholder="keep_monthly"
                @update:model-value="v => props.model.retention.keep_monthly = v ?? 0"
              />
            </el-col>
          </el-row>
          <div class="retention-hint">{{ t('plans.form.retentionHint') }}</div>
        </el-form-item>
      </el-col>
    </el-row>

    <el-divider content-position="left">{{ t('plans.form.source') }}</el-divider>

    <el-alert
      v-if="isPathBasedKind && selectedAgent && sourcePathMappings.length > 0"
      :title="t('plans.form.availableHostPaths')"
      type="info"
      :closable="false"
      show-icon
      class="source-path-alert"
    >
      <div class="source-path-roots">
        <el-tag v-for="mapping in sourcePathMappings" :key="mapping.host_path" size="small" effect="plain">
          {{ mapping.host_path }}
        </el-tag>
      </div>
    </el-alert>
    <el-alert
      v-else-if="isPathBasedKind && selectedAgent"
      :title="t('plans.form.pathMappingCompatibilityHint')"
      type="info"
      :closable="false"
      show-icon
      class="source-path-alert"
    />

    <template v-if="props.model.kind === 'filesystem'">
      <el-row :gutter="16">
        <el-col :span="24">
          <el-form-item :label="t('plans.form.paths')" prop="source.paths">
            <TagInput v-model="props.model.source.paths" :placeholder="t('plans.form.pathsPlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item :label="t('plans.form.excludes')" prop="source.excludes">
            <TagInput v-model="props.model.source.excludes" :placeholder="t('plans.form.excludesPlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item :label="t('plans.form.oneFileSystem')">
            <el-switch
              :model-value="props.model.source.one_file_system === true"
              :active-text="t('plans.form.yes')"
              :inactive-text="t('plans.form.no')"
              @update:model-value="(v) => (props.model.source.one_file_system = v === true)"
            />
          </el-form-item>
        </el-col>
      </el-row>
    </template>

    <template v-else-if="props.model.kind === 'sqlite'">
      <el-row :gutter="16">
        <el-col :span="24">
          <el-form-item :label="t('plans.form.databasePath')" prop="source.path">
            <el-input v-model="props.model.source.path" :placeholder="t('plans.form.databasePathPlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item :label="t('plans.form.estimatedDumpBytes')" prop="source.estimated_dump_bytes">
            <el-input-number
              :model-value="props.model.source.estimated_dump_bytes"
              :min="1"
              :step="1073741824"
              :controls-position="'right'"
              @update:model-value="(v) => (props.model.source.estimated_dump_bytes = v ?? undefined)"
            />
            <div class="hint">{{ t('plans.form.dumpBytesHint') }}</div>
          </el-form-item>
        </el-col>
      </el-row>
    </template>

    <template v-else>
      <el-row :gutter="16">
        <el-col :span="16">
          <el-form-item :label="t('plans.form.host')" prop="source.host">
            <el-input v-model="props.model.source.host" :placeholder="t('plans.form.hostPlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="8">
          <el-form-item :label="t('plans.form.port')" prop="source.port">
            <el-input-number
              :model-value="props.model.source.port"
              :min="1"
              :max="65535"
              :controls-position="'right'"
              @update:model-value="(v) => (props.model.source.port = v ?? undefined)"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item :label="t('plans.form.username')" prop="source.username">
            <el-input v-model="props.model.source.username" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item :label="t('plans.form.password')">
            <el-input
              v-model="props.model.source.password"
              type="password"
              show-password
              :placeholder="t('plans.form.passwordPlaceholder')"
            />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item :label="t('plans.form.database')" prop="source.database">
            <el-input v-model="props.model.source.database" :placeholder="t('plans.form.databasePlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="12">
          <el-form-item :label="t('plans.form.extraArgs')">
            <TagInput v-model="props.model.source.extra_args" :placeholder="t('plans.form.extraArgsPlaceholder')" />
          </el-form-item>
        </el-col>
        <el-col :span="24">
          <el-form-item :label="t('plans.form.estimatedDumpBytes')" prop="source.estimated_dump_bytes">
            <el-input-number
              :model-value="props.model.source.estimated_dump_bytes"
              :min="1"
              :step="1073741824"
              :controls-position="'right'"
              @update:model-value="(v) => (props.model.source.estimated_dump_bytes = v ?? undefined)"
            />
            <div class="hint">{{ t('plans.form.dumpBytesHint') }}</div>
          </el-form-item>
        </el-col>
        <template v-if="props.model.kind === 'mongodb'">
          <el-col :span="24">
            <el-form-item :label="t('plans.form.captureOplog')">
              <el-switch
                :model-value="props.model.source.capture_oplog === true"
                :active-text="t('plans.form.yes')"
                :inactive-text="t('plans.form.no')"
                @update:model-value="(v) => (props.model.source.capture_oplog = v === true)"
              />
            </el-form-item>
          </el-col>
        </template>
      </el-row>
    </template>
  </el-form>
  <div class="form-actions">
    <el-button @click="() => emit('cancel')">{{ t('common.cancel') }}</el-button>
    <el-button type="primary" :loading="props.submitting" @click="handleSubmit">{{ t('common.save') }}</el-button>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, type FormInstance, type FormRules } from 'element-plus'
import TagInput from './TagInput.vue'
import {
  CRON5_RE,
  CRON_PRESETS,
  IANA_TIMEZONES,
  KIND_LABELS,
  defaultSource,
} from './Constants'
import { translateEnum } from '@/i18n'
import type { Agent, Repository } from '@/api/types'
import { isAbsolutePath, isWithinMappedRoot } from '@/utils/pathMapping'
import type { PlanFormModel, PlanKind } from './Types'

const props = defineProps<{
  model: PlanFormModel
  agents: Agent[]
  repositories: Repository[]
  submitting: boolean
}>()
const emit = defineEmits<{
  (e: 'submit', model: PlanFormModel): void
  (e: 'cancel'): void
}>()

const { t } = useI18n()

function statusText(status: string): string {
  return translateEnum('status', status)
}

const formRef = ref<FormInstance | null>(null)

// Labels resolve at render time so a language switch updates open forms too.
const planKinds = computed(() =>
  Object.entries(KIND_LABELS).map(([value, key]) => ({
    value: value as PlanKind,
    label: t(key),
  })),
)

const cronPresets = computed(() =>
  CRON_PRESETS.map((p) => ({ value: p.value, label: t(p.key) })),
)

const filteredRepos = computed(() =>
  props.repositories.filter((r) => r.agent_id === props.model.agent_id),
)

const selectedAgent = computed(() =>
  props.agents.find((agent) => agent.id === props.model.agent_id),
)
const sourcePathMappings = computed(() => selectedAgent.value?.source_path_mappings ?? [])
const isPathBasedKind = computed(() =>
  props.model.kind === 'filesystem' || props.model.kind === 'sqlite',
)

function onKindChange(kind: PlanKind): void {
  props.model.source = defaultSource(kind)
}
function onAgentChange(): void {
  const repo = filteredRepos.value.find((r) => r.id === props.model.repository_id)
  if (repo && repo.agent_id !== props.model.agent_id) {
    props.model.repository_id = ''
  }
  void formRef.value?.validateField(['source.paths', 'source.path', 'source.excludes'])
}

function cronValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const s = typeof value === 'string' ? value : ''
  if (!s) { callback(new Error(t('plans.rules.scheduleRequired'))); return }
  if (!CRON5_RE.test(s)) callback(new Error(t('plans.rules.cronFields')))
  else callback()
}
function positiveNumberValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const n = typeof value === 'number' ? value : NaN
  if (!Number.isFinite(n) || n <= 0) callback(new Error(t('plans.rules.greaterThanZero')))
  else callback()
}
function portValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const n = typeof value === 'number' ? value : NaN
  if (!Number.isFinite(n) || n < 1 || n > 65535) callback(new Error(t('plans.rules.portRange')))
  else callback()
}
function isWithinSourceMappedRoot(path: string): boolean {
  return isWithinMappedRoot(path, sourcePathMappings.value)
}
function absolutePathValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const p = typeof value === 'string' ? value.trim() : ''
  if (!p) callback(new Error(t('plans.rules.pathRequired')))
  else if (!isAbsolutePath(p)) callback(new Error(t('plans.rules.absolutePath')))
  else if (!isWithinSourceMappedRoot(p)) callback(new Error(t('plans.rules.pathOutsideAllowedRoots')))
  else callback()
}
function pathsValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const items: unknown[] = Array.isArray(value) ? value : []
  const paths: string[] = items.filter((p): p is string => typeof p === 'string')
  if (paths.length === 0) callback(new Error(t('plans.rules.pathsRequired')))
  else if (paths.some((p) => !isAbsolutePath(p))) callback(new Error(t('plans.rules.pathsAbsolute')))
  else if (paths.some((p) => !isWithinSourceMappedRoot(p))) callback(new Error(t('plans.rules.pathsOutsideAllowedRoots')))
  else callback()
}
function excludesValidator(_rule: unknown, value: unknown, callback: (error?: string | Error) => void, ..._rest: unknown[]): void {
  const excludes: unknown[] = Array.isArray(value) ? value : []
  const invalid = excludes.some((exclude) =>
    typeof exclude === 'string' && isAbsolutePath(exclude) && !isWithinSourceMappedRoot(exclude),
  )
  if (invalid) callback(new Error(t('plans.rules.excludesOutsideAllowedRoots')))
  else callback()
}

const rules = computed<FormRules>(() => ({
  name: [{ required: true, message: t('plans.rules.nameRequired'), trigger: 'blur' }],
  agent_id: [{ required: true, message: t('plans.rules.agentRequired'), trigger: 'change' }],
  kind: [{ required: true, message: t('plans.rules.kindRequired'), trigger: 'change' }],
  repository_id: [{ required: true, message: t('plans.rules.repositoryRequired'), trigger: 'change' }],
  schedule: [{ validator: cronValidator, trigger: 'blur' }],
  timezone: [{ required: true, message: t('plans.rules.timezoneRequired'), trigger: 'change' }],
  timeout_seconds: [{ required: true, message: t('plans.rules.timeoutRequired'), trigger: 'change' }],
  source: {
    host: [{ required: true, message: t('plans.rules.hostRequired'), trigger: 'blur' }],
    port: [{ required: true, message: t('plans.rules.portRequired'), trigger: 'change' }, { validator: portValidator, trigger: 'change' }],
    username: [{ required: true, message: t('plans.rules.usernameRequired'), trigger: 'blur' }],
    database: [{ required: true, message: t('plans.rules.databaseRequired'), trigger: 'blur' }],
    estimated_dump_bytes: [{ validator: positiveNumberValidator, message: t('plans.rules.dumpBytesPositive'), trigger: 'change' }],
    path: [{ validator: absolutePathValidator, trigger: 'blur' }],
    paths: [{ validator: pathsValidator, trigger: 'change' }],
    excludes: [{ validator: excludesValidator, trigger: 'change' }],
  },
}))

async function handleSubmit(): Promise<void> {
  let valid = false
  try { valid = await formRef.value?.validate() ?? false } catch { valid = false }
  if (!valid) return
  const r = props.model.retention
  if (r.keep_last <= 0 && r.keep_daily <= 0 && r.keep_weekly <= 0 && r.keep_monthly <= 0) {
    ElMessage.warning(t('plans.form.retentionWarning'))
    return
  }
  emit('submit', props.model)
}
</script>

<style scoped>
.presets {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  align-items: center;
  margin-top: 6px;
}
.preset-label {
  font-size: 12px;
  color: #999;
}
.preset-tag {
  cursor: pointer;
}
.form-actions {
  padding: 12px 0 4px;
  border-top: 1px solid #f0f0f0;
  display: flex;
  justify-content: flex-end;
  gap: 8px;
}
.retention-hint {
  margin-top: 4px;
  font-size: 12px;
  color: #999;
}
.hint {
  margin-top: 4px;
  font-size: 12px;
  color: #999;
}
.source-path-alert {
  margin-bottom: 16px;
}
.source-path-roots {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-top: 8px;
}
</style>

// web/src/views/plans/PlanForm.tsx
import React, { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'
import { Separator } from '@/components/ui/separator'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { TagInput } from './TagInput'
import {
  CRON5_RE,
  CRON_PRESETS,
  IANA_TIMEZONES,
  KIND_LABELS,
  defaultSource,
} from './Constants'
import { translateEnum } from '@/i18n'
import type { Agent, Repository } from '@/api/types'
import { isAbsolutePath, isWithinMappedRoot } from '@/utils/pathMapping'
import type { PlanFormModel, PlanKind } from './Types'
import { toastWarning } from '@/lib/toast'
import { FolderTree, Loader2, Save, X } from 'lucide-react'

interface PlanFormProps {
  model: PlanFormModel
  onChange: (model: PlanFormModel) => void
  agents: Agent[]
  repositories: Repository[]
  submitting: boolean
  onSubmit: (model: PlanFormModel) => void
  onCancel: () => void
}

export const PlanForm: React.FC<PlanFormProps> = ({
  model,
  onChange,
  agents,
  repositories,
  submitting,
  onSubmit,
  onCancel,
}) => {
  const { t } = useTranslation()
  const [errors, setErrors] = useState<Record<string, string>>({})

  const selectedAgent = useMemo(() => agents.find((a) => a.id === model.agent_id), [agents, model.agent_id])
  const sourcePathMappings = useMemo(() => selectedAgent?.source_path_mappings ?? [], [selectedAgent])
  const isPathBasedKind = model.kind === 'filesystem' || model.kind === 'sqlite'

  const filteredRepos = useMemo(
    () => repositories.filter((r) => r.agent_id === model.agent_id),
    [repositories, model.agent_id]
  )

  const planKinds = useMemo(
    () =>
      Object.entries(KIND_LABELS).map(([value, key]) => ({
        value: value as PlanKind,
        label: t(key),
      })),
    [t]
  )

  const cronPresets = useMemo(
    () => CRON_PRESETS.map((p) => ({ value: p.value, label: t(p.key) })),
    [t]
  )

  const updateModel = (partial: Partial<PlanFormModel>) => {
    onChange({ ...model, ...partial })
  }

  const updateSource = (partial: Partial<PlanFormModel['source']>) => {
    onChange({ ...model, source: { ...model.source, ...partial } })
  }

  const updateRetention = (partial: Partial<PlanFormModel['retention']>) => {
    onChange({ ...model, retention: { ...model.retention, ...partial } })
  }

  const handleKindChange = (kind: PlanKind) => {
    onChange({
      ...model,
      kind,
      source: defaultSource(kind),
    })
  }

  const handleAgentChange = (agentId: string) => {
    const repo = filteredRepos.find((r) => r.id === model.repository_id)
    const newRepoId = repo && repo.agent_id === agentId ? model.repository_id : ''
    onChange({
      ...model,
      agent_id: agentId,
      repository_id: newRepoId,
    })
  }

  const validate = (): boolean => {
    const errs: Record<string, string> = {}

    if (!model.name.trim()) errs.name = t('plans.rules.nameRequired') || 'Plan name is required'
    if (!model.agent_id) errs.agent_id = t('plans.rules.agentRequired') || 'Agent is required'
    if (!model.kind) errs.kind = t('plans.rules.kindRequired') || 'Backup kind is required'
    if (!model.repository_id) errs.repository_id = t('plans.rules.repositoryRequired') || 'Repository is required'

    if (!model.schedule.trim()) {
      errs.schedule = t('plans.rules.scheduleRequired') || 'Schedule is required'
    } else if (!CRON5_RE.test(model.schedule.trim())) {
      errs.schedule = t('plans.rules.cronFields') || 'Invalid 5-field cron expression'
    }

    if (!model.timezone) errs.timezone = t('plans.rules.timezoneRequired') || 'Timezone is required'
    if (!model.timeout_seconds || model.timeout_seconds <= 0) {
      errs.timeout_seconds = t('plans.rules.timeoutRequired') || 'Timeout must be greater than 0'
    }

    // Source specific validation
    if (model.kind === 'filesystem') {
      const paths = model.source.paths ?? []
      if (paths.length === 0) {
        errs['source.paths'] = t('plans.rules.pathsRequired') || 'At least one backup path required'
      } else if (paths.some((p) => !isAbsolutePath(p))) {
        errs['source.paths'] = t('plans.rules.pathsAbsolute') || 'All backup paths must be absolute'
      } else if (paths.some((p) => !isWithinMappedRoot(p, sourcePathMappings))) {
        errs['source.paths'] = t('plans.rules.pathsOutsideAllowedRoots') || 'Path outside allowed host roots'
      }

      const excludes = model.source.excludes ?? []
      if (
        excludes.some(
          (ex) => isAbsolutePath(ex) && !isWithinMappedRoot(ex, sourcePathMappings)
        )
      ) {
        errs['source.excludes'] = t('plans.rules.excludesOutsideAllowedRoots') || 'Exclude outside allowed host roots'
      }
    } else if (model.kind === 'sqlite') {
      const p = model.source.path?.trim() ?? ''
      if (!p) {
        errs['source.path'] = t('plans.rules.pathRequired') || 'Database path is required'
      } else if (!isAbsolutePath(p)) {
        errs['source.path'] = t('plans.rules.absolutePath') || 'Database path must be absolute'
      } else if (!isWithinMappedRoot(p, sourcePathMappings)) {
        errs['source.path'] = t('plans.rules.pathOutsideAllowedRoots') || 'Path outside allowed host roots'
      }
    } else {
      // Database types
      if (!model.source.host?.trim()) errs['source.host'] = t('plans.rules.hostRequired') || 'Host is required'
      const port = model.source.port
      if (port == null || port < 1 || port > 65535) {
        errs['source.port'] = t('plans.rules.portRange') || 'Port must be between 1 and 65535'
      }
      if (!model.source.username?.trim()) errs['source.username'] = t('plans.rules.usernameRequired') || 'Username is required'
      if (!model.source.database?.trim()) errs['source.database'] = t('plans.rules.databaseRequired') || 'Database is required'
    }

    setErrors(errs)
    return Object.keys(errs).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (!validate()) return

    const r = model.retention
    if (r.keep_last <= 0 && r.keep_daily <= 0 && r.keep_weekly <= 0 && r.keep_monthly <= 0) {
      toastWarning(t('plans.form.retentionWarning') || 'At least one retention policy field must be set')
      return
    }

    onSubmit(model)
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* Name */}
        <div className="space-y-1.5">
          <Label htmlFor="plan-name" className="text-xs">
            {t('plans.form.name')} *
          </Label>
          <Input
            id="plan-name"
            value={model.name}
            onChange={(e) => updateModel({ name: e.target.value })}
            placeholder={t('plans.form.namePlaceholder') || 'e.g. Daily PostgreSQL Backup'}
            disabled={submitting}
            aria-describedby={errors.name ? 'plan-name-error' : undefined}
            className="h-9 text-xs"
          />
          {errors.name && (
            <p id="plan-name-error" className="text-[11px] text-destructive">
              {errors.name}
            </p>
          )}
        </div>

        {/* Kind */}
        <div className="space-y-1.5">
          <Label className="text-xs">{t('plans.form.kind')} *</Label>
          <Select
            value={model.kind}
            onValueChange={(val) => handleKindChange(val as PlanKind)}
            disabled={submitting}
          >
            <SelectTrigger className="h-9 text-xs">
              <SelectValue placeholder={t('plans.form.kindPlaceholder')} />
            </SelectTrigger>
            <SelectContent>
              {planKinds.map((k) => (
                <SelectItem key={k.value} value={k.value} className="text-xs">
                  {k.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.kind && <p className="text-[11px] text-destructive">{errors.kind}</p>}
        </div>

        {/* Agent */}
        <div className="space-y-1.5">
          <Label className="text-xs">{t('plans.form.agent')} *</Label>
          <Select
            value={model.agent_id}
            onValueChange={handleAgentChange}
            disabled={submitting}
          >
            <SelectTrigger className="h-9 text-xs">
              <SelectValue placeholder={t('plans.form.agent')} />
            </SelectTrigger>
            <SelectContent>
              {agents.map((a) => (
                <SelectItem key={a.id} value={a.id} className="text-xs">
                  <span>{a.name}</span>
                  <span className="ml-2 text-[10px] text-muted-foreground">
                    ({translateEnum('status', a.status)})
                  </span>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.agent_id && <p className="text-[11px] text-destructive">{errors.agent_id}</p>}
        </div>

        {/* Repository */}
        <div className="space-y-1.5">
          <Label className="text-xs">{t('plans.form.repository')} *</Label>
          <Select
            value={model.repository_id}
            onValueChange={(val) => updateModel({ repository_id: val })}
            disabled={submitting || filteredRepos.length === 0}
          >
            <SelectTrigger className="h-9 text-xs">
              <SelectValue placeholder={t('plans.form.repository')} />
            </SelectTrigger>
            <SelectContent>
              {filteredRepos.map((r) => (
                <SelectItem key={r.id} value={r.id} className="text-xs">
                  {r.storage_target_name} @ {r.agent_name}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.repository_id && (
            <p className="text-[11px] text-destructive">{errors.repository_id}</p>
          )}
        </div>

        {/* Schedule */}
        <div className="space-y-1.5">
          <Label htmlFor="plan-schedule" className="text-xs">
            {t('plans.form.schedule')} *
          </Label>
          <Input
            id="plan-schedule"
            value={model.schedule}
            onChange={(e) => updateModel({ schedule: e.target.value })}
            placeholder={t('plans.form.schedulePlaceholder') || '0 2 * * *'}
            disabled={submitting}
            aria-describedby={errors.schedule ? 'plan-schedule-error' : undefined}
            className="h-9 text-xs font-mono"
          />
          <div className="flex flex-wrap items-center gap-1.5 pt-1">
            <span className="text-[10px] text-muted-foreground">
              {t('plans.form.presets')}:
            </span>
            {cronPresets.map((p) => (
              <Badge
                key={p.value}
                variant="outline"
                onClick={() => updateModel({ schedule: p.value })}
                className="cursor-pointer text-[10px] px-1.5 py-0 hover:bg-primary/20 hover:text-primary transition-colors"
              >
                {p.label}
              </Badge>
            ))}
          </div>
          {errors.schedule && (
            <p id="plan-schedule-error" className="text-[11px] text-destructive">
              {errors.schedule}
            </p>
          )}
        </div>

        {/* Timezone */}
        <div className="space-y-1.5">
          <Label className="text-xs">{t('plans.form.timezone')} *</Label>
          <Select
            value={model.timezone}
            onValueChange={(val) => updateModel({ timezone: val })}
            disabled={submitting}
          >
            <SelectTrigger className="h-9 text-xs">
              <SelectValue placeholder={t('plans.form.timezonePlaceholder')} />
            </SelectTrigger>
            <SelectContent className="max-h-60">
              {IANA_TIMEZONES.map((tz) => (
                <SelectItem key={tz} value={tz} className="text-xs font-mono">
                  {tz}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {errors.timezone && <p className="text-[11px] text-destructive">{errors.timezone}</p>}
        </div>

        {/* Timeout Seconds */}
        <div className="space-y-1.5">
          <Label htmlFor="plan-timeout" className="text-xs">
            {t('plans.form.timeoutSeconds')} *
          </Label>
          <Input
            id="plan-timeout"
            type="number"
            min={1}
            step={60}
            value={model.timeout_seconds}
            onChange={(e) => updateModel({ timeout_seconds: Number(e.target.value) || 3600 })}
            disabled={submitting}
            aria-describedby={errors.timeout_seconds ? 'plan-timeout-error' : undefined}
            className="h-9 text-xs"
          />
          {errors.timeout_seconds && (
            <p id="plan-timeout-error" className="text-[11px] text-destructive">
              {errors.timeout_seconds}
            </p>
          )}
        </div>
      </div>

      {/* Retention Policy */}
      <div className="space-y-2 rounded-md border border-border bg-card/40 p-3">
        <Label className="text-xs font-semibold">{t('plans.form.retention')}</Label>
        <p className="text-[11px] text-muted-foreground">{t('plans.form.retentionHint')}</p>
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-1">
          <div className="space-y-1">
            <span className="text-[10px] text-muted-foreground">keep_last</span>
            <Input
              type="number"
              min={0}
              value={model.retention.keep_last}
              onChange={(e) => updateRetention({ keep_last: Number(e.target.value) || 0 })}
              className="h-8 text-xs font-mono"
            />
          </div>
          <div className="space-y-1">
            <span className="text-[10px] text-muted-foreground">keep_daily</span>
            <Input
              type="number"
              min={0}
              value={model.retention.keep_daily}
              onChange={(e) => updateRetention({ keep_daily: Number(e.target.value) || 0 })}
              className="h-8 text-xs font-mono"
            />
          </div>
          <div className="space-y-1">
            <span className="text-[10px] text-muted-foreground">keep_weekly</span>
            <Input
              type="number"
              min={0}
              value={model.retention.keep_weekly}
              onChange={(e) => updateRetention({ keep_weekly: Number(e.target.value) || 0 })}
              className="h-8 text-xs font-mono"
            />
          </div>
          <div className="space-y-1">
            <span className="text-[10px] text-muted-foreground">keep_monthly</span>
            <Input
              type="number"
              min={0}
              value={model.retention.keep_monthly}
              onChange={(e) => updateRetention({ keep_monthly: Number(e.target.value) || 0 })}
              className="h-8 text-xs font-mono"
            />
          </div>
        </div>
      </div>

      <Separator />

      {/* Source Details */}
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <FolderTree className="h-4 w-4 text-primary" />
          <h3 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
            {t('plans.form.source')}
          </h3>
        </div>

        {isPathBasedKind && selectedAgent && sourcePathMappings.length > 0 && (
          <Alert className="border-border/80 bg-muted/20 py-2.5 text-xs text-muted-foreground">
            <AlertTitle className="text-xs font-medium text-foreground">
              {t('plans.form.availableHostPaths')}
            </AlertTitle>
            <AlertDescription className="flex flex-wrap gap-1.5 mt-1">
              {sourcePathMappings.map((m) => (
                <Badge key={m.host_path} variant="secondary" className="font-mono text-[10px]">
                  {m.host_path}
                </Badge>
              ))}
            </AlertDescription>
          </Alert>
        )}

        {/* Filesystem */}
        {model.kind === 'filesystem' && (
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label className="text-xs">{t('plans.form.paths')} *</Label>
              <TagInput
                modelValue={model.source.paths ?? []}
                onChange={(val) => updateSource({ paths: val })}
                placeholder={t('plans.form.pathsPlaceholder')}
                disabled={submitting}
              />
              {errors['source.paths'] && (
                <p className="text-[11px] text-destructive">{errors['source.paths']}</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label className="text-xs">{t('plans.form.excludes')}</Label>
              <TagInput
                modelValue={model.source.excludes ?? []}
                onChange={(val) => updateSource({ excludes: val })}
                placeholder={t('plans.form.excludesPlaceholder')}
                disabled={submitting}
              />
              {errors['source.excludes'] && (
                <p className="text-[11px] text-destructive">{errors['source.excludes']}</p>
              )}
            </div>

            <div className="flex items-center justify-between rounded-md border border-border p-3">
              <div className="space-y-0.5">
                <Label className="text-xs">{t('plans.form.oneFileSystem')}</Label>
                <p className="text-[11px] text-muted-foreground">
                  {t('plans.form.oneFileSystemHint') || 'Do not cross filesystem boundaries'}
                </p>
              </div>
              <Switch
                checked={model.source.one_file_system === true}
                onCheckedChange={(checked) => updateSource({ one_file_system: checked })}
                disabled={submitting}
              />
            </div>
          </div>
        )}

        {/* SQLite */}
        {model.kind === 'sqlite' && (
          <div className="space-y-4">
            <div className="space-y-1.5">
              <Label htmlFor="sqlite-path" className="text-xs">
                {t('plans.form.databasePath')} *
              </Label>
              <Input
                id="sqlite-path"
                value={model.source.path ?? ''}
                onChange={(e) => updateSource({ path: e.target.value })}
                placeholder={t('plans.form.databasePathPlaceholder')}
                disabled={submitting}
                className="h-9 text-xs font-mono"
              />
              {errors['source.path'] && (
                <p className="text-[11px] text-destructive">{errors['source.path']}</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="sqlite-dump" className="text-xs">
                {t('plans.form.estimatedDumpBytes')}
              </Label>
              <Input
                id="sqlite-dump"
                type="number"
                min={1}
                step={1073741824}
                value={model.source.estimated_dump_bytes ?? ''}
                onChange={(e) =>
                  updateSource({
                    estimated_dump_bytes: e.target.value ? Number(e.target.value) : undefined,
                  })
                }
                disabled={submitting}
                className="h-9 text-xs"
              />
              <p className="text-[10px] text-muted-foreground">{t('plans.form.dumpBytesHint')}</p>
            </div>
          </div>
        )}

        {/* DB Types (PostgreSQL / MySQL / MongoDB) */}
        {model.kind !== 'filesystem' && model.kind !== 'sqlite' && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="db-host" className="text-xs">
                {t('plans.form.host')} *
              </Label>
              <Input
                id="db-host"
                value={model.source.host ?? ''}
                onChange={(e) => updateSource({ host: e.target.value })}
                placeholder={t('plans.form.hostPlaceholder') || '127.0.0.1'}
                disabled={submitting}
                className="h-9 text-xs"
              />
              {errors['source.host'] && (
                <p className="text-[11px] text-destructive">{errors['source.host']}</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="db-port" className="text-xs">
                {t('plans.form.port')} *
              </Label>
              <Input
                id="db-port"
                type="number"
                min={1}
                max={65535}
                value={model.source.port ?? ''}
                onChange={(e) =>
                  updateSource({ port: e.target.value ? Number(e.target.value) : undefined })
                }
                disabled={submitting}
                className="h-9 text-xs font-mono"
              />
              {errors['source.port'] && (
                <p className="text-[11px] text-destructive">{errors['source.port']}</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="db-user" className="text-xs">
                {t('plans.form.username')} *
              </Label>
              <Input
                id="db-user"
                value={model.source.username ?? ''}
                onChange={(e) => updateSource({ username: e.target.value })}
                disabled={submitting}
                className="h-9 text-xs"
              />
              {errors['source.username'] && (
                <p className="text-[11px] text-destructive">{errors['source.username']}</p>
              )}
            </div>

            <div className="space-y-1.5">
              <Label htmlFor="db-pass" className="text-xs">
                {t('plans.form.password')}
              </Label>
              <Input
                id="db-pass"
                type="password"
                autoComplete="new-password"
                value={model.source.password ?? ''}
                onChange={(e) => updateSource({ password: e.target.value })}
                placeholder={t('plans.form.passwordPlaceholder') || 'Leave empty to keep unchanged'}
                disabled={submitting}
                className="h-9 text-xs"
              />
            </div>

            <div className="space-y-1.5 sm:col-span-2">
              <Label htmlFor="db-name" className="text-xs">
                {t('plans.form.database')} *
              </Label>
              <Input
                id="db-name"
                value={model.source.database ?? ''}
                onChange={(e) => updateSource({ database: e.target.value })}
                placeholder={t('plans.form.databasePlaceholder')}
                disabled={submitting}
                className="h-9 text-xs"
              />
              {errors['source.database'] && (
                <p className="text-[11px] text-destructive">{errors['source.database']}</p>
              )}
            </div>

            <div className="space-y-1.5 sm:col-span-2">
              <Label className="text-xs">{t('plans.form.extraArgs')}</Label>
              <TagInput
                modelValue={model.source.extra_args ?? []}
                onChange={(val) => updateSource({ extra_args: val })}
                placeholder={t('plans.form.extraArgsPlaceholder')}
                disabled={submitting}
              />
            </div>

            {model.kind === 'mongodb' && (
              <div className="flex items-center justify-between rounded-md border border-border p-3 sm:col-span-2">
                <div className="space-y-0.5">
                  <Label className="text-xs">{t('plans.form.captureOplog')}</Label>
                  <p className="text-[11px] text-muted-foreground">
                    {t('plans.form.captureOplogHint') || 'Include point-in-time oplog dump'}
                  </p>
                </div>
                <Switch
                  checked={model.source.capture_oplog === true}
                  onCheckedChange={(checked) => updateSource({ capture_oplog: checked })}
                  disabled={submitting}
                />
              </div>
            )}
          </div>
        )}
      </div>

      <div className="flex items-center justify-end gap-2 pt-4">
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={onCancel}
          disabled={submitting}
          className="h-8 text-xs gap-1.5"
        >
          <X className="h-3.5 w-3.5" />
          {t('common.cancel')}
        </Button>
        <Button type="submit" size="sm" disabled={submitting} className="h-8 text-xs gap-1.5">
          {submitting ? (
            <Loader2 className="h-3.5 w-3.5 animate-spin" />
          ) : (
            <Save className="h-3.5 w-3.5" />
          )}
          {t('common.save')}
        </Button>
      </div>
    </form>
  )
}
