// web/src/views/plans/PlansView.vue
<template>
  <div>
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 16px">
      <div class="section-title" style="margin-bottom: 0">{{ t('nav.plans') }}</div>
      <div>
        <el-button type="primary" @click="openCreate">
          <el-icon><Plus /></el-icon>
          <span>{{ t('plans.newPlan') }}</span>
        </el-button>
        <el-button @click="refresh">
          <el-icon><Refresh /></el-icon>
          <span>{{ t('common.refresh') }}</span>
        </el-button>
      </div>
    </div>

    <div style="margin-bottom: 12px">
      <el-select
        v-model="filterAgentId"
        :placeholder="t('plans.filterByAgent')"
        clearable
        filterable
        style="width: 240px"
        @change="loadPlans"
      >
        <el-option v-for="a in agents" :key="a.id" :label="`${a.name} (${statusText(a.status)})`" :value="a.id" />
      </el-select>
    </div>

    <div v-if="error" class="error-state">
      <el-icon><Warning /></el-icon>
      <p>{{ error }}</p>
      <el-button type="primary" @click="refresh" style="margin-top: 12px">{{ t('common.retry') }}</el-button>
    </div>

    <div v-else-if="loading" style="text-align: center; padding: 40px">
      <el-icon class="is-loading"><Loading /></el-icon>
    </div>

    <el-table v-else :data="plans" stripe row-key="id" style="width: 100%">
      <el-table-column :label="t('common.name')">
        <template #default="{ row: p }">
          {{ p.name }}
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.kind')" width="110">
        <template #default="{ row: p }">
          <el-tag :type="KIND_TAG_TYPE[(p as Plan).kind]">{{ t(KIND_LABELS[(p as Plan).kind]) }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.schedule')" width="130">
        <template #default="{ row: p }">
          <code style="font-size: 12px">{{ p.schedule }}</code>
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.timezone')" width="140">
        <template #default="{ row: p }">
          {{ p.timezone }}
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.enabled')" width="80">
        <template #default="{ row: p }">
          <el-switch
            :model-value="p.enabled"
            :before-change="() => toggleEnabled(p as Plan)"
            inline-prompt
            :active-text="t('common.on')"
            :inactive-text="t('common.off')"
          />
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.repository')" min-width="150">
        <template #default="{ row: p }">
          <el-tooltip :content="repositoryFor(p as Plan)?.repository_path || ''" placement="top">
            <span>{{ repositoryFor(p as Plan)?.storage_target_name || p.repository_id }}</span>
          </el-tooltip>
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.path')" min-width="220">
        <template #default="{ row: p }">
          <el-tooltip :content="sourcePaths(p as Plan)" placement="top">
            <span class="plan-source-path">{{ sourcePaths(p as Plan) }}</span>
          </el-tooltip>
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.lastRunAt')" width="180">
        <template #default="{ row: p }">
          {{ formatDateTime((p as Plan).last_run_at) }}
        </template>
      </el-table-column>
      <el-table-column :label="t('plans.columns.timeout')" width="100">
        <template #default="{ row: p }">
          {{ p.timeout_seconds }}s
        </template>
      </el-table-column>
      <el-table-column :label="t('common.actions')" width="150" fixed="right">
        <template #default="{ row: p }">
          <el-button text size="small" :disabled="runningId === p.id" @click="runPlan(p as Plan)">
            <el-icon style="margin-right: 2px"><VideoPlay /></el-icon>
            {{ t('common.run') }}
          </el-button>
          <el-button text size="small" @click="startEdit(p as Plan)">
            <el-icon style="margin-right: 2px"><Edit /></el-icon>
            {{ t('common.edit') }}
          </el-button>
          <el-button text size="small" type="danger" @click="deletePlan(p as Plan)">
            <el-icon style="margin-right: 2px"><Delete /></el-icon>
            {{ t('common.delete') }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog
      v-model="dialogVisible"
      :title="editing ? t('plans.editPlan') : t('plans.newPlan')"
      width="720px"
      destroy-on-close
      @closed="dialogClosed"
    >
      <PlanForm
        :model="form"
        :agents="agents"
        :repositories="repositories"
        :submitting="saving"
        @submit="savePlan"
        @cancel="dialogVisible = false"
      />
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Plus, Refresh, Warning, Loading, VideoPlay, Edit, Delete } from '@element-plus/icons-vue'
import { apiDelete, apiGet, apiPost, apiPut } from '@/api/client'
import type { Agent, Plan, Repository, Run } from '@/api/types'
import { translateEnum } from '@/i18n'
import PlanForm from './PlanForm.vue'
import { KIND_LABELS, KIND_TAG_TYPE, defaultSource } from './Constants'
import { buildPayload, buildValidatePayload, type PlanFormModel, type ValidateResult } from './Types'

const router = useRouter()
const { t } = useI18n()

function statusText(status: string): string {
  return translateEnum('status', status)
}

const plans = ref<Plan[]>([])
const agents = ref<Agent[]>([])
const repositories = ref<Repository[]>([])
const filterAgentId = ref('')
const loading = ref(false)
const error = ref('')

const dialogVisible = ref(false)
const editing = ref(false)
const saving = ref(false)
const runningId = ref('')

function blankForm(): PlanFormModel {
  return {
    name: '',
    agent_id: '',
    kind: 'filesystem',
    schedule: '',
    timezone: 'UTC',
    enabled: true,
    source: defaultSource('filesystem'),
    repository_id: '',
    retention: { keep_last: 7, keep_daily: 7, keep_weekly: 4, keep_monthly: 3 },
    timeout_seconds: 3600,
  }
}
const form = reactive<PlanFormModel>(blankForm())

function repositoryFor(p: Plan): Repository | undefined {
  return repositories.value.find((r) => r.id === p.repository_id)
}
function sourcePaths(p: Plan): string {
  if (p.kind === 'filesystem') return p.source.paths?.join(', ') || '-'
  if (p.kind === 'sqlite') return p.source.path || '-'
  return [p.source.host, p.source.port, p.source.database].filter((value) => value !== undefined && value !== '').join(':') || '-'
}

function formatDateTime(value: string | null): string {
  if (!value) return '-'
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString()
}

function errorMessage(err: unknown): string {
  if (err instanceof Error) {
    const code = (err as Error & { code?: unknown }).code
    const codeStr = typeof code === 'string' && code ? code : ''
    return codeStr ? `${codeStr}: ${err.message}` : err.message
  }
  return String(err)
}

async function loadPlans(): Promise<void> {
  error.value = ''
  loading.value = true
  try {
    plans.value = await apiGet<Plan[]>('/plans', {
      agent_id: filterAgentId.value || undefined,
    })
  } catch (err: unknown) {
    error.value = errorMessage(err)
  } finally {
    loading.value = false
  }
}

async function loadMeta(): Promise<void> {
  try {
    const [agentList, repoList] = await Promise.all([
      apiGet<Agent[]>('/agents'),
      apiGet<Repository[]>('/repositories'),
    ])
    agents.value = agentList
    repositories.value = repoList
  } catch (err: unknown) {
    error.value = errorMessage(err)
  }
}

async function refresh(): Promise<void> {
  await Promise.all([loadPlans(), loadMeta()])
}

onMounted(() => {
  void refresh()
})

function openCreate(): void {
  Object.assign(form, blankForm())
  editing.value = false
  dialogVisible.value = true
}

function startEdit(row: Plan): void {
  Object.assign(form, {
    id: row.id,
    name: row.name,
    agent_id: row.agent_id,
    kind: row.kind,
    schedule: row.schedule,
    timezone: row.timezone,
    enabled: row.enabled,
    source: { ...row.source, password: '' },
    repository_id: row.repository_id,
    retention: { ...row.retention },
    timeout_seconds: row.timeout_seconds,
  })
  editing.value = true
  dialogVisible.value = true
}

function dialogClosed(): void {
  runningId.value = ''
}

async function toggleEnabled(row: Plan): Promise<boolean> {
  const target = !row.enabled
  try {
    await apiPut(`/plans/${row.id}`, {
      ...buildPayload({
        ...row,
        source: { ...row.source },
        retention: { ...row.retention },
      }),
      enabled: target,
    })
    row.enabled = target
    return true
  } catch (err: unknown) {
    ElMessage.error(errorMessage(err))
    return false
  }
}

async function runPlan(row: Plan): Promise<void> {
  runningId.value = row.id
  try {
    const run = await apiPost<Run>(`/plans/${row.id}/run`, {})
    await router.push(`/runs/${run.id}`)
  } catch (err: unknown) {
    ElMessage.error(errorMessage(err))
    runningId.value = ''
  }
}

async function deletePlan(row: Plan): Promise<void> {
  try {
    await ElMessageBox.confirm(
      t('plans.deleteDialog.confirm', { name: row.name }),
      t('plans.deleteDialog.title'),
      { type: 'warning', confirmButtonText: t('common.delete'), cancelButtonText: t('common.cancel') },
    )
  } catch {
    return
  }
  try {
    await apiDelete(`/plans/${row.id}`)
    ElMessage.success(t('plans.deleted'))
    await loadPlans()
  } catch (err: unknown) {
    const e = err as { code?: string; message?: string }
    if (e.code === 'plan_has_snapshots' || e.code === 'conflict') {
      ElMessage.warning(t('plans.deleteDialog.snapshotsRequired'))
      return
    }
    ElMessage.error(errorMessage(err))
  }
}

async function savePlan(model: PlanFormModel): Promise<void> {
  saving.value = true
  try {
    const result = await apiPost<ValidateResult>('/plans/validate', buildValidatePayload(model))
    if (!result.ok) {
      const code = result.code || 'validation_failed'
      const msg = result.message || t('plans.validationFailed')
      ElMessage.error(`${code}: ${msg}`)
      return
    }
    if (editing.value && model.id) {
      await apiPut(`/plans/${model.id}`, buildPayload(model))
      ElMessage.success(t('plans.updated'))
    } else {
      await apiPost('/plans', buildPayload(model))
      ElMessage.success(t('plans.created'))
    }
    dialogVisible.value = false
    await loadPlans()
  } catch (err: unknown) {
    ElMessage.error(errorMessage(err))
  } finally {
    saving.value = false
  }
}
</script>

// web/src/views/plans/PlansView.tsx
import React, { useEffect, useState, useMemo } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { Card, CardContent } from '@/components/ui/card'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import { apiGet, apiPost, apiPut, apiDelete, isApiClientError } from '@/api/client'
import { translateEnum, formatDateTime } from '@/i18n'
import type { Plan, Agent, Repository, Run } from '@/api/types'
import { AppEmptyState } from '@/components/AppEmptyState'
import { AppErrorState } from '@/components/AppErrorState'
import { StatusBadge, type BadgeTone } from '@/components/StatusBadge'
import { PageLoadingState } from '@/components/PageLoadingState'
import { ConfirmActionDialog } from '@/components/ConfirmActionDialog'
import { toastSuccess, toastError, toastWarning } from '@/lib/toast'
import { PlanForm } from './PlanForm'
import { KIND_LABELS, defaultSource } from './Constants'
import {
  buildPayload,
  buildValidatePayload,
  type PlanFormModel,
  type ValidateResult,
} from './Types'
import { Plus, RefreshCw, Play, Edit2, Trash2, Loader2 } from 'lucide-react'

const KIND_TONE_MAP: Record<string, BadgeTone> = {
  filesystem: 'default',
  postgresql: 'secondary',
  mysql: 'secondary',
  mongodb: 'secondary',
  sqlite: 'outline',
}

function blankForm(): PlanFormModel {
  return {
    name: '',
    agent_id: '',
    kind: 'filesystem',
    schedule: '',
    timezone: 'UTC',
    enabled: true,
    source: defaultSource('filesystem'),
    repository_id: '',
    retention: { keep_last: 7, keep_daily: 7, keep_weekly: 4, keep_monthly: 3 },
    timeout_seconds: 3600,
  }
}

export const PlansView: React.FC = () => {
  const { t } = useTranslation()
  const navigate = useNavigate()

  const [plans, setPlans] = useState<Plan[]>([])
  const [agents, setAgents] = useState<Agent[]>([])
  const [repositories, setRepositories] = useState<Repository[]>([])

  const [filterAgentId, setFilterAgentId] = useState<string>('all')
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState(false)
  const [saving, setSaving] = useState(false)
  const [formModel, setFormModel] = useState<PlanFormModel>(blankForm())

  const [runningId, setRunningId] = useState<string | null>(null)
  const [toggleLoading, setToggleLoading] = useState<Record<string, boolean>>({})

  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false)
  const [planToDelete, setPlanToDelete] = useState<Plan | null>(null)

  const loadPlans = async (agentId?: string) => {
    setLoading(true)
    setError(null)
    try {
      const selectedAgent = agentId === 'all' || !agentId ? undefined : agentId
      const data = await apiGet<Plan[]>('/plans', { agent_id: selectedAgent })
      setPlans(data)
    } catch (err: unknown) {
      setError(isApiClientError(err) ? err.message : t('plans.loadFailed'))
    } finally {
      setLoading(false)
    }
  }

  const loadMeta = async () => {
    try {
      const [agentList, repoList] = await Promise.all([
        apiGet<Agent[]>('/agents'),
        apiGet<Repository[]>('/repositories'),
      ])
      setAgents(agentList)
      setRepositories(repoList)
    } catch {
      // Non-blocking
    }
  }

  useEffect(() => {
    loadPlans()
    loadMeta()
  }, [])

  const handleAgentFilterChange = (agentId: string) => {
    setFilterAgentId(agentId)
    loadPlans(agentId)
  }

  const repositoryMap = useMemo(() => {
    const map = new Map<string, Repository>()
    for (const r of repositories) {
      map.set(r.id, r)
    }
    return map
  }, [repositories])

  const agentMap = useMemo(() => {
    const map = new Map<string, Agent>()
    for (const a of agents) {
      map.set(a.id, a)
    }
    return map
  }, [agents])

  const sourcePaths = (plan: Plan): string => {
    if (plan.kind === 'filesystem') {
      return plan.source.paths?.join(', ') ?? '—'
    }
    if (plan.kind === 'sqlite') {
      return plan.source.path ?? '—'
    }
    const host = plan.source.host ?? ''
    const db = plan.source.database ?? ''
    return host ? `${host}/${db}` : db || '—'
  }

  const openCreate = () => {
    setEditing(false)
    const init = blankForm()
    if (agents.length > 0) init.agent_id = agents[0].id
    const availableRepo = repositories.find((r) => r.agent_id === init.agent_id)
    if (availableRepo) init.repository_id = availableRepo.id
    setFormModel(init)
    setDialogOpen(true)
  }

  const startEdit = (plan: Plan) => {
    setEditing(true)
    setFormModel({
      id: plan.id,
      name: plan.name,
      agent_id: plan.agent_id,
      kind: plan.kind,
      schedule: plan.schedule,
      timezone: plan.timezone,
      enabled: plan.enabled,
      source: { ...plan.source },
      repository_id: plan.repository_id,
      retention: { ...plan.retention },
      timeout_seconds: plan.timeout_seconds,
    })
    setDialogOpen(true)
  }

  const toggleEnabled = async (plan: Plan) => {
    const nextState = !plan.enabled
    setToggleLoading((prev) => ({ ...prev, [plan.id]: true }))
    try {
      await apiPut(`/plans/${plan.id}`, { enabled: nextState })
      setPlans((prev) =>
        prev.map((p) => (p.id === plan.id ? { ...p, enabled: nextState } : p))
      )
      toastSuccess(nextState ? t('plans.enabled') : t('plans.disabled'))
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('plans.statusUpdateFailed'))
    } finally {
      setToggleLoading((prev) => ({ ...prev, [plan.id]: false }))
    }
  }

  const runPlan = async (plan: Plan) => {
    setRunningId(plan.id)
    try {
      const runRes = await apiPost<Run>(`/plans/${plan.id}/run`, {})
      toastSuccess(t('plans.runDispatched'))
      navigate(`/runs/${runRes.id}`)
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('plans.runFailed'))
      setRunningId(null)
    }
  }

  const openDeleteDialog = (plan: Plan) => {
    setPlanToDelete(plan)
    setDeleteDialogOpen(true)
  }

  const handleDeleteConfirm = async () => {
    if (!planToDelete) return
    try {
      await apiDelete(`/plans/${planToDelete.id}`)
      toastSuccess(t('plans.deleted'))
      await loadPlans(filterAgentId)
    } catch (err: unknown) {
      if (isApiClientError(err) && (err.code === 'plan_has_snapshots' || err.code === 'conflict')) {
        toastWarning(t('plans.deleteDialog.snapshotsRequired'))
      } else {
        toastError(isApiClientError(err) ? err.message : t('plans.deleteFailed'))
      }
    }
  }

  const handleSavePlan = async (model: PlanFormModel) => {
    setSaving(true)
    try {
      // Validate with agent if applicable
      try {
        const valPayload = buildValidatePayload(model)
        const valRes = await apiPost<ValidateResult>('/plans/validate', valPayload)
        if (!valRes.ok) {
          toastError(valRes.message || t('plans.form.validationFailed'))
          setSaving(false)
          return
        }
      } catch (valErr: unknown) {
        // Validation check failed to communicate or rejected
        toastError(isApiClientError(valErr) ? valErr.message : t('plans.form.validationFailed'))
        setSaving(false)
        return
      }

      const payload = buildPayload(model)
      if (editing && model.id) {
        await apiPut(`/plans/${model.id}`, payload)
        toastSuccess(t('plans.saved'))
      } else {
        await apiPost('/plans', payload)
        toastSuccess(t('plans.created'))
      }
      setDialogOpen(false)
      await loadPlans(filterAgentId)
    } catch (err: unknown) {
      toastError(isApiClientError(err) ? err.message : t('plans.saveFailed'))
    } finally {
      setSaving(false)
    }
  }

  if (loading) {
    return <PageLoadingState />
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-foreground">
            {t('nav.plans')}
          </h2>
          <p className="text-xs text-muted-foreground">
            {t('plans.subtitle')}
          </p>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" onClick={openCreate} className="h-8 text-xs gap-1.5 bg-primary text-primary-foreground">
            <Plus className="h-3.5 w-3.5" aria-hidden="true" />
            {t('plans.newPlan')}
          </Button>
          <Button
            variant="outline"
            size="sm"
            onClick={() => loadPlans(filterAgentId)}
            className="h-8 text-xs gap-1.5"
          >
            <RefreshCw className="h-3.5 w-3.5" aria-hidden="true" />
            {t('common.refresh')}
          </Button>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <Select value={filterAgentId} onValueChange={handleAgentFilterChange}>
          <SelectTrigger className="w-56 h-8 text-xs">
            <SelectValue placeholder={t('plans.filterByAgent')} />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all" className="text-xs">
              {t('common.allAgents')}
            </SelectItem>
            {agents.map((a) => (
              <SelectItem key={a.id} value={a.id} className="text-xs">
                {a.name} ({translateEnum('status', a.status)})
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {error ? (
        <AppErrorState
          title={t('nav.plans')}
          message={error}
          onRetry={() => loadPlans(filterAgentId)}
        />
      ) : (
        <Card className="border-border bg-card/60 shadow-sm">
          <CardContent className="p-0">
            {plans.length > 0 ? (
              <div className="rounded-md overflow-hidden">
                {/* Desktop table */}
                <div className="hidden md:block overflow-x-auto">
                  <Table className="min-w-[850px]">
                    <TableHeader>
                      <TableRow className="border-border hover:bg-transparent">
                        <TableHead className="text-xs font-medium">{t('common.name')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.kind')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.schedule')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.enabled')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.repository')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.path')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.lastRunAt')}</TableHead>
                        <TableHead className="text-xs font-medium">{t('plans.columns.timeout')}</TableHead>
                        <TableHead className="text-xs font-medium text-right">{t('common.actions')}</TableHead>
                      </TableRow>
                    </TableHeader>
                    <TableBody>
                      {plans.map((plan) => {
                        const repo = repositoryMap.get(plan.repository_id)
                        const isRunning = runningId === plan.id
                        const isToggling = toggleLoading[plan.id] || false
                        return (
                          <TableRow key={plan.id} className="border-border hover:bg-muted/30">
                            <TableCell className="font-medium text-xs text-foreground">
                              {plan.name}
                            </TableCell>
                            <TableCell className="text-xs">
                              <StatusBadge tone={KIND_TONE_MAP[plan.kind] || 'default'}>
                                {t(KIND_LABELS[plan.kind])}
                              </StatusBadge>
                            </TableCell>
                            <TableCell className="text-xs">
                              <div className="flex flex-col font-mono text-[11px] leading-tight">
                                <span className="text-foreground">{plan.schedule}</span>
                                <span className="text-[10px] text-muted-foreground">{plan.timezone}</span>
                              </div>
                            </TableCell>
                            <TableCell className="text-xs">
                              <Switch
                                checked={plan.enabled}
                                disabled={isToggling}
                                onCheckedChange={() => toggleEnabled(plan)}
                              />
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <span className="cursor-help underline decoration-dotted underline-offset-2">
                                    {repo?.storage_target_name || plan.repository_id}
                                  </span>
                                </TooltipTrigger>
                                <TooltipContent className="text-[11px] font-mono">
                                  {repo?.repository_path || 'No path available'}
                                </TooltipContent>
                              </Tooltip>
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground max-w-xs truncate">
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <span className="truncate block font-mono text-[11px]">
                                    {sourcePaths(plan)}
                                  </span>
                                </TooltipTrigger>
                                <TooltipContent className="text-[11px] max-w-sm break-all font-mono">
                                  {sourcePaths(plan)}
                                </TooltipContent>
                              </Tooltip>
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground">
                              {plan.last_run_at ? formatDateTime(plan.last_run_at) : '—'}
                            </TableCell>
                            <TableCell className="text-xs text-muted-foreground font-mono">
                              {plan.timeout_seconds}s
                            </TableCell>
                            <TableCell className="text-xs text-right">
                              <div className="flex items-center justify-end gap-1">
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  disabled={isRunning}
                                  className="h-7 text-xs text-primary gap-1"
                                  onClick={() => runPlan(plan)}
                                >
                                  {isRunning ? (
                                    <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
                                  ) : (
                                    <Play className="h-3 w-3" aria-hidden="true" />
                                  )}
                                  {t('common.run')}
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-7 text-xs text-muted-foreground hover:text-foreground gap-1"
                                  onClick={() => startEdit(plan)}
                                >
                                  <Edit2 className="h-3 w-3" aria-hidden="true" />
                                  {t('common.edit')}
                                </Button>
                                <Button
                                  variant="ghost"
                                  size="sm"
                                  className="h-7 text-xs text-rose-600 dark:text-rose-400 hover:text-rose-700 dark:hover:text-rose-300 gap-1"
                                  onClick={() => openDeleteDialog(plan)}
                                  aria-label={t('common.delete')}
                                >
                                  <Trash2 className="h-3 w-3" aria-hidden="true" />
                                  {t('common.delete')}
                                </Button>
                              </div>
                            </TableCell>
                          </TableRow>
                        )
                      })}
                    </TableBody>
                  </Table>
                </div>

                {/* Mobile cards */}
                <div className="md:hidden divide-y divide-border">
                  {plans.map((plan) => {
                    const agent = agentMap.get(plan.agent_id)
                    const isRunning = runningId === plan.id
                    const isToggling = toggleLoading[plan.id] || false
                    return (
                      <div key={plan.id} className="p-3 space-y-2 text-xs">
                        <div className="flex items-center justify-between gap-2">
                          <span className="font-semibold text-foreground text-xs">{plan.name}</span>
                          <StatusBadge tone={KIND_TONE_MAP[plan.kind] || 'default'}>
                            {t(KIND_LABELS[plan.kind])}
                          </StatusBadge>
                        </div>
                        <div className="flex items-center justify-between text-[11px] text-muted-foreground">
                          <span>Agent: {agent?.name || plan.agent_id}</span>
                          <div className="flex items-center gap-2">
                            <span className="font-mono">{plan.schedule}</span>
                            <Switch
                              checked={plan.enabled}
                              disabled={isToggling}
                              onCheckedChange={() => toggleEnabled(plan)}
                            />
                          </div>
                        </div>
                        <div className="flex items-center justify-end gap-1 pt-1">
                          <Button
                            variant="outline"
                            size="sm"
                            disabled={isRunning}
                            className="h-7 text-xs text-primary gap-1"
                            onClick={() => runPlan(plan)}
                          >
                            {isRunning ? (
                              <Loader2 className="h-3 w-3 animate-spin" aria-hidden="true" />
                            ) : (
                              <Play className="h-3 w-3" aria-hidden="true" />
                            )}
                            {t('common.run')}
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 text-xs text-muted-foreground hover:text-foreground gap-1"
                            onClick={() => startEdit(plan)}
                          >
                            <Edit2 className="h-3 w-3" aria-hidden="true" />
                            {t('common.edit')}
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="h-7 text-xs text-rose-600 dark:text-rose-400 hover:text-rose-700 dark:hover:text-rose-300 gap-1"
                            onClick={() => openDeleteDialog(plan)}
                            aria-label={t('common.delete')}
                          >
                            <Trash2 className="h-3.5 w-3.5" aria-hidden="true" />
                            {t('common.delete')}
                          </Button>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            ) : (
              <div className="p-8">
                <AppEmptyState
                  title={t('plans.emptyPlans')}
                  description={t('plans.emptyPlans_desc')}
                />
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Create / Edit Plan Dialog */}
      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-2xl max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle className="text-sm font-semibold">
              {editing ? t('plans.editPlan') : t('plans.newPlan')}
            </DialogTitle>
            <DialogDescription className="text-xs">
              {t('plans.form.description')}
            </DialogDescription>
          </DialogHeader>
          <div className="pt-2">
            <PlanForm
              model={formModel}
              onChange={setFormModel}
              agents={agents}
              repositories={repositories}
              submitting={saving}
              onSubmit={handleSavePlan}
              onCancel={() => setDialogOpen(false)}
            />
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirm Dialog */}
      <ConfirmActionDialog
        open={deleteDialogOpen}
        onOpenChange={setDeleteDialogOpen}
        title={t('plans.deleteDialog.title')}
        description={
          planToDelete
            ? t('plans.deleteDialog.confirm', { name: planToDelete.name })
            : ''
        }
        destructive
        onConfirm={handleDeleteConfirm}
      />
    </div>
  )
}
