// web/src/views/plans/TagInput.tsx
import React, { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { Badge } from '@/components/ui/badge'
import { Input } from '@/components/ui/input'
import { X } from 'lucide-react'

interface TagInputProps {
  modelValue?: string[]
  onChange: (value: string[]) => void
  placeholder?: string
  disabled?: boolean
}

export const TagInput: React.FC<TagInputProps> = ({
  modelValue = [],
  onChange,
  placeholder,
  disabled = false,
}) => {
  const { t } = useTranslation()
  const [draft, setDraft] = useState('')

  const placeholderText = placeholder ?? t('common.tagInputPlaceholder')

  const add = () => {
    const trimmed = draft.trim()
    setDraft('')
    if (!trimmed) return
    if (modelValue.includes(trimmed)) return
    onChange([...modelValue, trimmed])
  }

  const removeAt = (index: number) => {
    const next = [...modelValue]
    next.splice(index, 1)
    onChange(next)
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      e.preventDefault()
      add()
    }
  }

  return (
    <div className="w-full space-y-2">
      {modelValue.length > 0 && (
        <div className="flex flex-wrap gap-1.5">
          {modelValue.map((item, index) => (
            <Badge
              key={`${index}-${item}`}
              variant="secondary"
              className="text-xs px-2 py-0.5 font-mono gap-1"
            >
              <span>{item}</span>
              {!disabled && (
                <button
                  type="button"
                  onClick={() => removeAt(index)}
                  className="rounded-full hover:bg-muted p-0.5 transition-colors"
                  aria-label={t('common.removeTag', { tag: item })}
                >
                  <X className="h-3 w-3 text-muted-foreground hover:text-foreground" aria-hidden="true" />
                </button>
              )}
            </Badge>
          ))}
        </div>
      )}
      <Input
        value={draft}
        onChange={(e) => setDraft(e.target.value)}
        onKeyDown={handleKeyDown}
        onBlur={add}
        placeholder={placeholderText}
        disabled={disabled}
        className="h-8 text-xs font-mono"
      />
    </div>
  )
}

// web/src/views/plans/TagInput.vue
<template>
  <div class="tag-input">
    <div v-if="(props.modelValue?.length ?? 0) > 0" class="tag-list">
      <el-tag v-for="(item, index) in props.modelValue" :key="`${index}-${item}`" closable size="small" @close="removeAt(index)">
        {{ item }}
      </el-tag>
    </div>
    <el-input
      v-model="draft"
      size="small"
      :placeholder="placeholderText"
      @keydown.enter.prevent="add"
      @blur="add"
    />
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'

const props = defineProps<{
  modelValue?: string[]
  placeholder?: string
}>()

const { t } = useI18n()

const placeholderText = computed(() => props.placeholder ?? t('common.tagInputPlaceholder'))

const emit = defineEmits<{
  (e: 'update:modelValue', value: string[]): void
}>()

const draft = ref('')

function add(): void {
  const value = draft.value.trim()
  draft.value = ''
  if (!value) return
  if (props.modelValue?.includes(value)) return
  emit('update:modelValue', [...(props.modelValue ?? []), value])
}

function removeAt(index: number): void {
  const next = [...(props.modelValue ?? [])]
  next.splice(index, 1)
  emit('update:modelValue', next)
}
</script>

<style scoped>
.tag-input {
  width: 100%;
}
.tag-list {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  margin-bottom: 8px;
}
</style>
